### PR TITLE
Eliminate use of Travis on 2.0 branch in favor of GHA for testing

### PR DESCRIPTION
**Pull request by westonruter**
Travis is super slow because travis-ci.org is deprecated and being turned down. It's too painful to bare any longer.

### CODE REVIEW

**Comment by westonruter** [comment]
@pierlon There's surely a more elegant way to accomplish the integration of the lib tests with your GHA masterpiece, so please amend as you see fit!

**Comment by westonruter** [comment]
I largely copied all the relevant code from `develop`, removed dead code, and then tweaked `build-test-measure.yml`.

**Comment by westonruter** [comment]
The difference:

`git diff origin/develop..add/gha-2.0 -- .github/workflows/build-test-measure.yml`

```diff
diff --git a/.github/workflows/build-test-measure.yml b/.github/workflows/build-test-measure.yml
index f22a34045..917073e04 100644
--- a/.github/workflows/build-test-measure.yml
+++ b/.github/workflows/build-test-measure.yml
@@ -109,7 +109,9 @@ jobs:
             ${{ runner.os }}-composer-
 
       - name: Install Composer dependencies
-        run: composer install --prefer-dist --optimize-autoloader --no-progress --no-interaction
+        run: |
+          composer self-update --1
+          composer install --prefer-dist --optimize-autoloader --no-progress --no-interaction
 
       - name: Validate composer.json
         run: composer --no-interaction validate --no-check-all
@@ -151,7 +153,9 @@ jobs:
             ${{ runner.os }}-composer-
 
       - name: Install Composer dependencies
-        run: composer install
+        run: |
+          composer self-update --1
+          composer install
 
       - name: Static Analysis (PHPStan)
         run: vendor/bin/phpstan analyse
@@ -239,7 +243,9 @@ jobs:
           CI: true
 
       - name: Install Composer dependencies
-        run: composer install --prefer-dist --optimize-autoloader --no-progress --no-interaction
+        run: |
+          composer self-update --1
+          composer install --prefer-dist --optimize-autoloader --no-progress --no-interaction
 
       - name: Build plugin
         run: |
@@ -330,7 +336,7 @@ jobs:
         uses: shivammathur/setup-php@v2
         with:
           php-version: ${{ matrix.php }}
-          extensions: curl, date, dom, gd, iconv, json, libxml, mysql, spl
+          extensions: curl, date, dom, gd, iconv, json, libxml, mysql, spl, zip
           coverage: ${{ matrix.coverage && 'pcov' || 'none' }}
           ini-values: pcov.directory=.
 
@@ -356,7 +362,11 @@ jobs:
             ${{ runner.os }}-composer-
 
       - name: Install Composer dependencies
-        run: composer install --prefer-dist --ignore-platform-reqs --no-progress --no-interaction
+        run: |
+          composer self-update --1
+          composer install --prefer-dist --ignore-platform-reqs --no-progress --no-interaction
+          composer --working-dir=lib/common install --prefer-dist --ignore-platform-reqs --no-progress --no-interaction
+          composer --working-dir=lib/optimizer install --prefer-dist --ignore-platform-reqs --no-progress --no-interaction
 
       - name: Get npm cache directory
         id: npm-cache
@@ -405,8 +415,32 @@ jobs:
 
       - name: Run tests
         if: ${{ matrix.coverage == false }}
+        working-directory: ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp
         run: vendor/bin/phpunit
+
+      - name: Run lib/common and lib/optimizer tests
+        if: ${{ matrix.coverage == false }}
+        working-directory: ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp
+        run: |
+          export PATH="$(pwd)/vendor/bin:$PATH"
+          echo "Common tests"
+          composer --working-dir=lib/common run-script unit
+          echo "Optimizer tests"
+          composer --working-dir=lib/optimizer run-script unit
+
+      - name: Run lib/common and lib/optimizer linting
         working-directory: ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp
+        if: ${{ matrix.php == '7.4' }}
+        run: |
+          export PATH="$(pwd)/vendor/bin:$PATH"
+          echo "Linting lib/common"
+          composer --working-dir=lib/common run-script lint
+          composer --working-dir=lib/common run-script cs
+          composer --working-dir=lib/common run-script analyze
+          echo "Linting lib/optimizer"
+          composer --working-dir=lib/optimizer run-script lint
+          composer --working-dir=lib/optimizer run-script cs
+          composer --working-dir=lib/optimizer run-script analyze
 
       - name: Run tests with coverage
         if: ${{ matrix.coverage == true }}
@@ -464,7 +498,9 @@ jobs:
       - name: Install Composer dependencies
         # Scripts are not ignored as they are needed to apply patches for the
         # `sabberworm/php-css-parser` dependency.
-        run: composer install --prefer-dist --optimize-autoloader
+        run: |
+          composer self-update --1
+          composer install --prefer-dist --optimize-autoloader
 
       - name: Get npm cache directory
         id: npm-cache

```

**Comment by pierlon** [comment]
I've moved the library related tests to their own jobs to keep things simple, with the added benefit that they are now run in parallel and should save few seconds on overall CI runtime.

**Review by pierlon — APPROVED** [review]
LGTM!

**Comment by westonruter** [comment]
Thank you!

**Pull request merged**
