### PR TITLE
Add support for Composer v2

### LINKED ISSUE #5551: Composer 2 Support
## Feature description

Looks like some dependencies need to be updated to fully support Composer 2.

For example `cweagans/composer-patches` added support in version 1.7. There's a PR for updating it: #5474. But it fails because of a seemingly unrelated issue with Facebook's oEmbed changing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

See #5551

- Eliminates forcing Composer v1 to be used in CI
- Updates composer.lock to be Composer v2 compatible

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Review by westonruter — APPROVED** [review]

**Comment by westonruter** [comment]
Approved other than the build errors.

**Comment by pierlon** [comment]
Investigating why CI build is failing...

**Comment by pierlon** [comment]
Turns out to be a bug in Composer: https://github.com/composer/composer/issues/9463. This is blocked until a new release is made.

**Comment by pierlon** [comment]
Builds are now passing with Composer v2.0.7 being used :tada:.

**Comment by westonruter** [comment]
Great work!

**Comment by westonruter** [comment]
@pierlon did you intend for this to be merged into the `2.0` branch?

**Comment by pierlon** [comment]
Yes, I forgot to mention that actually. I was hoping we could make this apart of `2.0.6` so that it could resolve https://github.com/google/web-stories-wp/issues/5083.

**Comment by westonruter** [comment]
OK, could you open a separate PR for the `2.0` branch then with the commits cherry picked? They don't merge cleanly.

**Comment by pierlon** [comment]
Will do.

**Pull request merged**
