### PR TITLE
Improve font sizes in onboarding wizard and settings screen

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

* Reduce `font-size` of heading in theme cards to `1rem`.
* Set `font-size` of `h3` to consistently be `1.2rem` regardless of viewport width.

Before | After
-------|-----
before-resized | after-resized

👇  See comments below for additional changes.

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Review by amedina — APPROVED** [review]
Very nice in terms proportionality and consistency. Ship it!

**Comment by westonruter** [comment]
A couple more fixes for Analytics:

Before | After
-------|------
before-analytics | after-analytics-2

**Comment by westonruter** [comment]
Also improved Plugin Suppression on mobile viewport:

Before | After
-------|------
before-plugin-suppression | after-plugin-suppression

**Comment by jwold** [comment]
Looks much better!

**Comment by amedina** [comment]
Yeah; much better.

**Comment by westonruter** [comment]
Also fixing toggle margins on mobile:

Before | After
-------|-----
Screen Shot 2020-08-06 at 16 33 58 | Screen Shot 2020-08-06 at 16 34 13

**Comment by westonruter** [comment]
Added initial fix for cramped buttons on Moto G4:

Before | After
-------|------
image | image

For fuller fix, see #5193.

**Comment by westonruter** [comment]
Removed `margin-left` from `amp-info` because when the text fills the horizontal space there can be less margin on the right:

Before | After
-------|-----
desktop-before | desktop-after
mobile-before | mobile-after

**Comment by westonruter** [comment]
Improved margin for mobile redirection toggle:

Before | After
-------|------
Screen Shot 2020-08-06 at 17 26 59 | Screen Shot 2020-08-06 at 17 28 30

**Comment by westonruter** [comment]
Improved styling of welcome buttons:

Device | Before | After
--------|-------|------
Desktop | desktop-before | desktop-after
Mobile | mobile-before | mobile-after

**Comment by amedina** [comment]
All these changes look great! Significant improvements. 

One question: the `Supported templates` section is showing a single part (e.g. content types)?

**Comment by westonruter** [comment]
> One question: the `Supported templates` section is showing a single part (e.g. content types)?

Ah yes. This is just hidden because I selected Legacy. I should have selected a Reader theme so that supported templates would be shown.

**Review by amedina — APPROVED** [review]
Significant improvements indeed.

**Comment by jwold** [comment]
@westonruter I didn't see anything on desktop that stood out to me. On mobile I found a number of issues that we may want to address:

MOBILE - ONBOARDING

- [ ] ~Center align header on mobile? https://d.pr/i/ArQRjV~
- [ ] Add lines between stepper: https://d.pr/i/2xw00O
- [x] Onboarding step 1 - Large gap at bottom: https://d.pr/i/oqFZby
- [ ] ~Auto collapse template modes on mobile? https://d.pr/i/s2xlzB~
- [x] Template modes: Equal margin on left/right https://d.pr/i/HWNjrm
- [ ] Move up info circle? https://d.pr/i/IQ5TZc
- [ ] Match all margins so that they're 25px? https://d.pr/i/o1BF1k
- [x] Seeing some alignment issues: https://d.pr/i/TuSkq7

MOBILE - SETTINGS 

- [ ] Tweaks overall: https://d.pr/i/GHQahS
- [x] Shrink space in supported templates: https://d.pr/i/N6iF9i
- [ ] Separate idea to change a bunch of headline sizes: https://d.pr/i/5EhSCm

Granted, some of these are not related to fonts, but if we think they're worth doing I can open a new issue for them.

cc @amedina

**Comment by westonruter** [comment]
> * Center align header on mobile? https://d.pr/i/ArQRjV

Center align in what way? I think this looks ok to me.

> * Seeing some alignment issues: https://d.pr/i/TuSkq7

And what should the resolution be? Hide the warning labels on mobile?

**Comment by westonruter** [comment]
Removed welcome illustration on mobile.

Before | After
-------|------
Screen Shot 2020-08-07 at 20 08 51 | Screen Shot 2020-08-07 at 20 10 38

**Comment by westonruter** [comment]
> * Separate idea to change a bunch of headline sizes: https://d.pr/i/5EhSCm

Problem: Those are `h3` headings, and if they are reduced to `1rem` (16px) then they'd be the same size as the `h4` headings:

image

**Comment by westonruter** [comment]
Fixed supported templates gap.

Before | After
-------|------
supported-templates-gap-before | supported-templates-gap-after

**Comment by westonruter** [comment]
Hid template mode notices on mobile. Fixed line wrapping of Reader theme drawer.

Before | After
-------|------
template-modes-before | template-modes-after

**Comment by westonruter** [comment]
> * Auto collapse template modes on mobile? https://d.pr/i/s2xlzB

I think since these template modes are the only ones shown on the screen, it is OK to be expanded by default. It also ensures the notices are displayed.

**Comment by westonruter** [comment]
Fixed left/right margins.

Device | Before | After
-------|--------|------
Desktop | desktop-left-right-margins-before | desktop-left-right-margins-after
Mobile | mobile-left-right-margins-before | mobile-left-right-margins-after

**Comment by jwold** [comment]
> Center align in what way? I think this looks ok to me.

I'm ok with keeping it as is. Was thinking we would move the objects to the middle of the screen on mobile. 

> And what should the resolution be? Hide the warning labels on mobile?

Agreed, that makes the most sense to me. 

> Those are h3 headings, and if they are reduced to 1rem (16px) then they'd be the same size as the h4 headings:

If they semantically need to be h3 and h4, then I agree it makes sense to keep them different sizes.

**Pull request merged**
