### PR TITLE
Check for `conflicts.user` property before rendering list item

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

Amends #6374.

If there isn't a user with the same slug as the AMP slug, the settings screen crashes.

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Review by westonruter — APPROVED** [review]
Ooops. Thanks!

**Comment by pierlon** [comment]
Wait one more thing, the CI job to build the zips isn't running.

**Comment by pierlon** [comment]
There we go!

image

**Comment by westonruter** [comment]
**QA Passed**

Deleting the `amp` user and leaving other entity conflicts results in no error but the expected entities being listed:

image

**Pull request merged**
