### PR TITLE
Run spec update to add support for amp-mathml, amp-riddle-quiz, amp-wistia-player, amp-byside-content, amp-bind-macro

### LINKED ISSUE #941: Sanitizers should not strip valid 'amp-mathml' tags
AMP recently introduced support for MathML via the `amp-mathml` tag - https://www.ampproject.org/docs/reference/components/amp-mathml. When trying to add this tag to a WordPress site, I'm seeing mathml tags stripped by the amp-wp sanitizer. 

If I add this to `class-amp-allowed-tags-generated.php` everything works as expected, how do I go about adding this to the plugin correctly? I couldn't tell how the file is currently generated, if I can get some direction happy to add a pull request to add this support.

```
		'amp-mathml' => array(
			array(
				'attr_spec_list' => array(
					'data-formula' => array(
						'mandatory' => true,
					),
				),
				'tag_spec' => array(
					'html_format' => array(
							'amp',
					),
					'spec_url' => 'https://www.ampproject.org/docs/reference/components/amp-mathml',
				),

			),
		),

```

### PR DESCRIPTION
**Pull request by adamsilverstein**
Includes updates to other elements and attributes in the validator spec.

Fixes #941

### CODE REVIEW

**Comment by westonruter** [comment]
@adamsilverstein does this successfully result in `amp-mathml` elements not being removed? 

Could you add a test to `test-tag-and-attribute-sanitizer.php` to verify that a valid `amp-mathml` element survives validation and also that the sanitizer automatically picks up the `amp-mathml` component script?

For example:

https://github.com/Automattic/amp-wp/blob/c701b0b8614e4b454bf620950018d0f143796d3c/tests/test-tag-and-attribute-sanitizer.php#L156-L160

**Comment by adamsilverstein** [comment]
It should, I see the tags added to the generated file: https://github.com/Automattic/amp-wp/pull/943/files#diff-a761ebd1d4f764d95add0829d1378635R1325 

I'll add some tests for this and other new amp-html tags I see added to the validation file.

**Comment by adamsilverstein** [comment]
@westonruter I added tests for the new components I see in the pr that had matching docs at https://www.ampproject.org/docs/reference/components - namely amp-mathml, amp-riddle-quiz,  amp-wistia-player, amp-byside-content & amp-bind-macro. I tried amp-facebook-page, but I think it is too new and not in production (https://github.com/ampproject/amphtml/blob/9673d3fe860d5d61eb9b1193fc2a49b59cdf094c/extensions/amp-facebook-page/amp-facebook-page.md), the test failed so I removed it.

**Comment by westonruter** [comment]
Behold: `amp-mathml` rendered in a WordPress post!

image

**Pull request merged**
