### PR TITLE
Add export exclusions to gitattributes file

### PR DESCRIPTION
**Pull request by schlessera**
This is a hotfix to exclude test folders from the externalizable libraries.

The spec tests within these libraries that we pull in from the Node.js toolbox contain paths with emojis, which break when being extracted by the `unzip` tool on Mac OS X.

Related: https://github.com/ampproject/amp-toolbox-php/issues/47

### CODE REVIEW

**Review by westonruter — APPROVED** [review]

**Comment by pierlon** [comment]
Is Composer supposed to adhere to the `.gitattributes` file when checking out from GitHub as well? The spec tests are still included if I reference this PR. Here's a demo `composer.json`, for example (based on the config from the Web Stories plugin):

```json
{
  "name": "foo/bar",
  "require": {
    "ampproject/amp-wp": "dev-fix/prune-spec-test-files#a5c6b31"
  },
  "provide": {
    "ampproject/common": "dev-develop",
    "ampproject/optimizer": "dev-develop"
  },
  "config": {
    "discard-changes": true,
    "platform": {
      "php": "5.6"
    },
    "sort-packages": true
  },
  "autoload": {
    "psr-4": {
      "AmpProject\\": "vendor/ampproject/amp-wp/lib/common/src",
      "AmpProject\\Optimizer\\": "vendor/ampproject/amp-wp/lib/optimizer/src"
    }
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/ampproject/amp-wp",
      "no-api": true
    }
  ],
  "minimum-stability": "dev",
  "prefer-stable": true
}
```

**Comment by westonruter** [comment]
If it's a `git clone` then I'd hope not, as then the repo would be left in a dirty state.

**Comment by pierlon** [comment]
Yes, but I'm not seeing how this will fix the issue for the Web Stories plugin, or for any project that requires the plugin via GitHub for that matter. Composer will be using what's on the 2.0 branch, no?

**Comment by westonruter** [comment]
Isn't the issue with unzipping an archive that has emoji filenames? If using `git clone` then no unzipping would be performed.

**Comment by pierlon** [comment]
Oh right, yes. I got a bit confused there.

**Review by pierlon — APPROVED** [review]

**Pull request merged**
