### PR TITLE
Fix phpstan v0.12.99 static analysis failures

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

Some commits cherry-picked from #6456.

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Review by pierlon — APPROVED** [review]
LGTM.

**Comment by pierlon** [comment]
Just a note, there's another error this PR doesn't resolve but it only occurs with PHP 8:

image

We could resolve that in https://github.com/ampproject/amp-wp/pull/6466 if needs be.

**Comment by westonruter** [comment]
> We could resolve that in #6466 if needs be.

Yes, please do.

**Comment by westonruter** [comment]
Oh, I forgot that change was part of the other PR as well: https://github.com/ampproject/amp-wp/pull/6456/files#r673052243.

Well, if I merge the page caching PR first, then it won't need to be part of #6466. If not, then it will 😄

**Pull request merged**
