### PR TITLE
Mustache is a logic-less template syntax

### PR DESCRIPTION
**Pull request by luigitec**
Per: https://www.ampproject.org/docs/reference/components/amp-mustache

### CODE REVIEW

**Comment by luigitec** [comment]
Well, unit tests need to be updated as well.

**Comment by mjangda** [comment]
Thanks for the PR! As noted, test failures are unrelated (tracking in #699).

**Comment by JoeMittler** [comment]
@mjangda would like to point out that you have a PHP closing tag on line 21 that should be moved to the end of line 22.

**Comment by luigitec** [comment]
My bad, I edited the file directly on GH https://github.com/Automattic/amp-wp/pull/701

**Pull request merged**
