### PR TITLE
[amp-stories sub-task] Prepopulate Page block.

### LINKED ISSUE #1531: Blocks > Creating a new Page block should have a block template with  a background image layer (populated with a default image)  and  a vertical grid layer
**As an author creating a new AMP story page, I want the default block template to have a background image layer and a vertical grid layer. The background layer should be populated with a default image**
 - [x] _AC 1:_ When creating a new AMP story page the default template will include the following elements:
   - [x]  A background image layer block populated with a default image
   - [x]  A vertical grid layer on top of the  background image layer 
 - [x] _AC 2:_  AMP story author can update/change the image in the background from the default image to another background image of their choosing.

### PR DESCRIPTION
**Pull request by miina**
Fixes #1531.

Prepopulates page block with the following:
- Image Background Layer;
- Vertical Layer + paragraph;

Todo:
- [x] Adjust style to fill the whole layer with the gray image selector in case of Background Image and Background Video layers;

### CODE REVIEW

**Comment by nielslange** [comment]
@shoppingandmore2017 I've seen that you approved @miina's changes a few hours ago. Besides that, I've seen that you've approved various PRs on several repositories and created various empty issues. It seems like you're practising on how to use Github. Please try to do these exercises in our own repositories to avoid confusion in other repositories. 

@westonruter Is it intended that everyone can review and approve changed within this repo? Doesn't that lead to the risk that the code quality drops or insufficient checked PRs get accidentally approved?

**Comment by westonruter** [comment]
@nielslange AFAIK GitHub allows anyone to approve PRs, even non-contributors. However, their approvals aren't substantive as they don't allow a PR to be merged if that is required. In any case, the account was apparently deleted due to spammy behavior.

**Comment by mehigh** [comment]
@miina beyond the improvements to the height of the blocks, I've also improved the spacing of core blocks inside of the vertical:
Here's the before: http://cloud.urldocs.com/6921822d8209
And the after: http://cloud.urldocs.com/538925a8ddc4
The dotted lines overlaying the sibling blocks was confusing.

**Comment by mehigh** [comment]
Also I think due to the complexity we got with the ability to select the layer beneath the vertical for a later image upload we should create a new bug and look at that edge case separately.

**Comment by mehigh** [comment]
The last thing - if we can keep the is-selected class of the element we have in focus after we start clicking in the amp story all our problems should be gone:
https://dsh.re/2de3e

**Comment by mehigh** [comment]
I fixed the conflict, now it's ready for testing.

**Pull request merged**
