### PR TITLE
Update generated tags file to 767

### PR DESCRIPTION
**Pull request by miina**
PR for testing -- looks like updating the file makes the test fails.

### CODE REVIEW

**Comment by westonruter** [comment]
Updating the file from what state? The latest amphtml tag? I've identified an issue with the script where it is checking out the most recent tag and not necessarily the most recent stable release.

**Comment by miina** [comment]
@westonruter I just checked out `1.0`, run the `amphtml-update.sh` and committed the changes.

Was there anything else that should have been done?

**Comment by westonruter** [comment]
The last time I did it, I had to comment out these two lines:

https://github.com/Automattic/amp-wp/blob/b748977321cc3769d0476ceede56c39aa2fed267/bin/amphtml-update.sh#L35-L36

The reason being that the latest tag is not actually the latest stable release, as can be seen at https://github.com/ampproject/amphtml/releases

image

So I manually switched to the latest release tag when I did it. In practice this is probably overkill.

But as can be seen in https://github.com/ampproject/amphtml/pull/19214, the `amp-script` component was commented-out a couple weeks ago. That is why `amp-script` is now failing in the unit tests. So we just need to remove the `amp-script` test.

**Comment by kienstra** [comment]
**Request For Review**

Hi @westonruter,
Could you please review this? It applies your suggestion of [removing the test](https://github.com/Automattic/amp-wp/pull/1665/commits/8dbbe502dd970ebf8820e53f247c89d94c68cb43) for `<amp-script>`, and it [adds a test](https://github.com/Automattic/amp-wp/pull/1665/commits/29f29d7d6161f0af20a5eb2f2bfc15f7c5f0821a) for the newly-allowed element `<amp-delight-player>`. 

Thanks, Weston 😄

**Pull request merged**
