### PR TITLE
Fix `npm run test:php` errors in wp-env package

### LINKED ISSUE #7263: Running `npm run test:php` is broken after wp-env update to wp-env 5.0.0
### Bug Description

With the update to wp-env 5.0.0, running `npm run test:php` now results in a fatal error. This package update had a backwards-incompatible change as explained in the [release notes](https://github.com/WordPress/gutenberg/blob/trunk/packages/env/CHANGELOG.md#500-2022-07-27):

> ### Breaking Changes
> -   Removed the `WP_PHPUNIT__TESTS_CONFIG` environment variable from the `phpunit` container. **This removes automatic support for the `wp-phpunit/wp-phpunit` Composer package. To continue using the package, set the following two environment variables in your `phpunit.xml` file or similar: `WP_TESTS_DIR=""` and `WP_PHPUNIT__TESTS_CONFIG="/wordpress-phpunit/wp-tests-config.php"`.**
> -   Removed the generated `/var/www/html/phpunit-wp-config.php` file from the environment.

We didn't catch it via CI because GHA doesn't run Docker to run the tests. When running in the local Docker-based dev environment, however, it is broken.

### Expected Behaviour

Running PHPUnit tests, both `npm run test:php` and `npm run test:php:xdebug`, should work successfully.

### Screenshots

```
$ npm run test:php

> amp-wp@ test:php /home/westonruter/repos/amp
> wp-env run phpunit 'WORDPRESS_TABLE_PREFIX=wptests_ WP_TESTS_DIR=/var/www/wordpress-develop/tests/phpunit /var/www/html/wp-content/plugins/amp/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/amp/phpunit.xml.dist $npm_config_args'

ℹ Starting 'WORDPRESS_TABLE_PREFIX=wptests_ WP_TESTS_DIR=/var/www/wordpress-develop/tests/phpunit /var/www/html/wp-content/plugins/amp/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/amp/phpunit.xml.dist $npm_config_args' on the phpunit container. 

Starting aabe871bb4b92d5867707c9f76aa7c03_tests-mysql_1 ... done
Starting aabe871bb4b92d5867707c9f76aa7c03_tests-wordpress_1 ... done

wp_die() called
Message: <p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/support/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a></p>
Title: WordPress &rsaquo; Error
Args:
        response: 500
        code: internal_server_error
        exit: 
        back_link: 
        link_url: 
        link_text: 
        text_direction: ltr
        charset: UTF-8
        additional_errors: array (
)
```

### PHP Version

_No response_

### Plugin Version

2.3.0

### AMP plugin template mode

Standard, Transitional, Reader

### WordPress Version

_No response_

### Site Health

_No response_

### Gutenberg Version

_No response_

### OS(s) Affected

_No response_

### Browser(s) Affected

_No response_

### Device(s) Affected

_No response_

### Acceptance Criteria

_No response_

### Implementation Brief

_No response_

### QA Testing Instructions

_No response_

### Demo

_No response_

### Changelog Entry

_No response_

### PR DESCRIPTION
**Pull request by thelovekesh**
With the update to wp-env 5.0.0, running `npm run test:php` now results in a fatal error. After `@wordpress/env 5.0` you need to define `WP_PHPUNIT__TESTS_CONFIG` env for WP Tests config file.

See package [release notes](https://github.com/WordPress/gutenberg/blob/trunk/packages/env/CHANGELOG.md#500-2022-07-27).

## Summary

Fixes #7263 

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by thelovekesh** [comment]
Note: Running `WordPress/wordpress-develop#trunk` tests suite with WordPress 6.0 causes an internal server error. While changing it to `WordPress/wordpress-develop#6.0` works fine. Similarly defining core property in wp-env config to `"core": "WordPress/WordPress#master",` works fine with  `WordPress/wordpress-develop#trunk`.

**Comment by westonruter** [comment]
> Note: Running `WordPress/wordpress-develop#trunk` tests suite with WordPress 6.0 causes an internal server error. While changing it to `WordPress/wordpress-develop#6.0` works fine. Similarly defining core property in wp-env config to `"core": "WordPress/WordPress#master",` works fine with `WordPress/wordpress-develop#trunk`.

OK, so does `core` then need to be updated in `.wp-env.json`? As it stands right now, this PR is giving me the following error:

```
$ npm run test:php

> amp-wp@ test:php /home/westonruter/repos/amp
> wp-env run phpunit 'env WP_PHPUNIT__TESTS_CONFIG=/wordpress-phpunit/wp-tests-config.php WORDPRESS_TABLE_PREFIX=wptests_ WP_TESTS_DIR=/var/www/wordpress-develop/tests/phpunit /var/www/html/wp-content/plugins/amp/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/amp/phpunit.xml.dist $npm_config_args'

ℹ Starting 'env WP_PHPUNIT__TESTS_CONFIG=/wordpress-phpunit/wp-tests-config.php WORDPRESS_TABLE_PREFIX=wptests_ WP_TESTS_DIR=/var/www/wordpress-develop/tests/phpunit /var/www/html/wp-content/plugins/amp/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/amp/phpunit.xml.dist $npm_config_args' on the phpunit container. 

Starting aabe871bb4b92d5867707c9f76aa7c03_tests-mysql_1 ... done
Starting aabe871bb4b92d5867707c9f76aa7c03_tests-wordpress_1 ... done
Error: wp-tests-config.php is missing! Please use wp-tests-config-sample.php to create a config file.
```

**Comment by thelovekesh** [comment]
@westonruter Can you please confirm once if your `node_modules` are not stale? With the current `@wordpress/env: "5.2.0"` package I am getting the following results:

image

Confirmed the wp-env version with `npm run wp-env -- --version`
image

**Comment by thelovekesh** [comment]
> OK, so does core then need to be updated in .wp-env.json? As it stands right now, this PR is giving me the following error:

By default, wp-env considers the latest WP release and its matching test suite from the trunk and its compatible PHPUnit version which in the case right now is `6.0`. We are currently providing custom tests dir which is from `wordpress-develop`.

My thoughts are:
- Either keep the core and tests from master and trunk branches.
- Or let them be default as resolved by the package itself. 

In the wiki/docs, we can refer the user to `wp-env` docs so they can provide custom core/test versions according to their needs.

**Comment by westonruter** [comment]
I just did the following:

1. `npm install`
2. `npm run wp-env destroy`
3. `npm run start`
4. `npm run test:php`

And I get the same internal server error I got above.

When I run `npm run wp-env -- --version` I also get `5.2.0`.

So I don't know what's going on. I'll look a bit deeper.

In terms of testing, we should default to the latest stable version of WordPress. Testing against `trunk` (i.e. nightly) will be unstable.

**Comment by westonruter** [comment]
Strange. The error I'm getting is:

> Failed opening required '/var/www/html//wp-includes/class-wpdb.php

Indeed, there is no `class-wpdb.php` file in `~/.wp-env/aabe871bb4b92d5867707c9f76aa7c03/tests-WordPress/wp-includes`. The file is instead `wp-db.php`. 

There seems to be a version mismatch problem here. It seems `tests-WordPress` is using WordPress 6.0.2, whereas `wordpress-develop` is running `6.1-beta1-54282-src`. 

Compare these two lines:

https://github.com/WordPress/wordpress-develop/blob/0e924d96aaff3ad5000f9c9f2aa4998419d75284/tests/phpunit/includes/install.php#L43
https://github.com/WordPress/wordpress-develop/blob/6.0.2/tests/phpunit/includes/install.php#L43

The change seems to have come from https://github.com/WordPress/wordpress-develop/commit/fdb6e13fedc46fc19852479bad2488c9eab1ed9f as part of [WPCORE-56268](https://core.trac.wordpress.org/ticket/56268). So the problem is that the test suite PHP includes is coming from `6.1-beta1-54282-src` which is trying to load `wp-db.php` which does not exist in WordPress 6.0.2. 

If the version is made consistent then this problem would be fixed.

**Comment by thelovekesh** [comment]
@westonruter Exactly.  Have you tried changing the `wordpress-develop` mapping to `WordPress/wordpress-develop#6.0`? It will work fine.

Or, with the trunk tests specify `"core": "WordPress/WordPress#master"`, it should work perfectly.

**Comment by thelovekesh** [comment]
@westonruter My idea is to keep the latest stable WP version in our config. Later if anyone wants to run tests on another version, they can define a `.wp-env.override.json` and specify their configs. 

After https://github.com/ampproject/amp-wp/pull/7264/commits/84162d041a6bbca032315fc2e84ea8edcfdb3322 I tried running tests with WP 5.6 in `.wp-env.override.json` and everything works fine.

```json
{
  "core": "WordPress/WordPress#5.6"
}
```

**Comment by westonruter** [comment]
With the latest changes, it's working now. Nevertheless, it still doesn't seem all the versions are in sync. Inside of my `npm run wp-env install-path`, I'm seeing:

```
$ ack 'wp_version =' $(find . -name version.php)
WordPress/wp-includes/version.php
19:$wp_version = '6.0';

wordpress-develop/src/wp-includes/version.php
19:$wp_version = '6.0.3-alpha-54035-src';

tests-WordPress/wp-includes/version.php
19:$wp_version = '6.0';
```

> My idea is to keep the latest stable WP version in our config.

The problem is that it is installing WP `6.0` but the current stable version is actually `6.0.2`. 

I don't see a way to reference the latest stable version.

Can the three copies of WP all be set to be `trunk`?

**Comment by thelovekesh** [comment]
> Can the three copies of WP all be set to be trunk?

Yes, it's possible. In that case we need to specify the core as `WordPress/WordPress#master` and wordpress-develop mapping as `WordPress/wordpress-develop#trunk`.

With this combination, running `ack 'wp_version =' $(find . -name version.php)` at installed path gives:
```bash
wordpress-develop/src/wp-includes/version.php
19:$wp_version = '6.1-beta1-54282-src';

WordPress/wp-includes/version.php
19:$wp_version = '6.1-beta1-54285';

tests-WordPress/wp-includes/version.php
19:$wp_version = '6.1-beta1-54285';
```

I am a little confused about the `wp_version` in `wordpress-develop` though, not sure how things get updated on the git side from trac.

Try changes at https://github.com/ampproject/amp-wp/pull/7264/commits/1bf9ab381d533056cabedb2339345487b541649f.

---

Thanks for the `ack` trick. Looks cool.

**Comment by westonruter** [comment]
Excellent. I'm seeing:

```
WordPress/wp-includes/version.php
19:$wp_version = '6.1-beta1-54288';

wordpress-develop/src/wp-includes/version.php
19:$wp_version = '6.1-beta1-54282-src';

tests-WordPress/wp-includes/version.php
19:$wp_version = '6.1-beta1-54288';
```

I can see that r54288 is https://github.com/WordPress/wordpress-develop/commit/ac8cccac67a8f61e74824716507851e237826f4d which is the current `HEAD` of `trunk` on GitHub.

It is indeed strange about r54282. Not sure why it is 6 revisions behind.

Anyway, it's working much better now so I'm merging. Thanks!

**Review by westonruter — APPROVED** [review]

**Comment by westonruter** [comment]
> It is indeed strange about r54282. Not sure why it is 6 revisions behind.

[These](https://core.trac.wordpress.org/log/trunk?action=stop_on_copy&mode=stop_on_copy&rev=54288&stop_rev=54282&limit=100&sfp_email=&sfph_mail=) are differing revisions:

image

Perhaps one of the copies of WP is using a nightly build pegged at the most recent beta release?

**Comment by thelovekesh** [comment]
I think trac and git trunk are not in sync. Probably they got synced nightly? I will check it tomorrow, to check if both are in sync.

**Pull request merged**
