### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

The following dependencies cannot be updated as yet:

- The `webpack` dependency cannot be updated to v5 as yet until the Gutenberg packages we use support it (currently being worked on in https://github.com/WordPress/gutenberg/pull/26382);

- The `terser-webpack-plugin` dependency cannot be updated to v5 as it needs `webpack` v5;

- The `phpdocumentor/reflection` dependency cannot be updated to v4 due to incompatible PHP version constraints (and even if it were updated our current doc generation command will break).

Apart from that, the [localheinz/composer-normalize](https://packagist.org/packages/localheinz/composer-normalize) dependency (used in the Travis lint job) has been abandoned and is replaced with its successor, [ergebnis/composer-normalize](https://packagist.org/packages/ergebnis/composer-normalize). The dependency is locked to v2.9.0 as the latest release (v2.9.1) has dropped support for Composer v1.

Other miscellaneous changes:
- The Renovate config has been removed in preparation for migrating to Dependabot. That closes #4875;
- The `webpack-cli` dependency has been removed as it does not seem to be in use by the plugin.

<details>

<summary>
In total, 51 dependencies are updated.
</summary>

- babel-plugin-inline-react-svg to v1.1.2, closes #5550
- jest-silent-reporter to v0.3.0, closes #5542
- rtlcss-webpack-plugin to v4.0.4, closes #5536
- eslint-plugin-react-hooks to v4.2.0, closes #5527
- actions/cache action to v2, 5526
- postcss to v8.1.4, closes #5519
- lint-staged to v10.5.1, closes #5512
- xwp/wp-dev-lib to v1.6.5, closes #5510
- @babel/polyfill to v7.12.1, closes #5508
- @babel/plugin-proposal-class-properties to v7.12.1, closes #5507
- rtlcss to v2.6.1, closes #5505
- @babel/core to v7.12.3,  closes #5504
- @babel/cli to v7.12.1, closes #5502
- css-loader to v5, closes #5501
- eslint to v7.12.1, closes #5492
- copy-webpack-plugin to v6.2.1, closes #5490
- source-map-loader to v1.1.2, closes #5489
- mini-css-extract-plugin to v1, closes #5488
- postcss-loader to v4.0.4, closes #5487
- eslint-plugin-jsdoc to v30.7.5, closes #5484
- cweagans/composer-patches to v1.7.0, closes #5474
- moment to v2.29.1, closes #5473
- @wordpress/components to v11, closes #5472
- @wordpress/url to v2.19.0, closes #5471
- @wordpress/jest-puppeteer-axe to v1.10.0, closes #5470
- @wordpress/hooks to v2.10.0, closes #5469
- @wordpress/eslint-plugin to v7.3.0, closes #5468
- @wordpress/autop to v2.10.0, closes #5467
- @wordpress/block-editor to v5, closes #5466
- eslint-plugin-jest to v24.1.0, closes #5465
- babel-jest to v26.6.1, closes #5460
- uuid to v8.3.1, closes #5458
- eslint-plugin-react to v7.21.5, closes #5456
- @wordpress/edit-post to v3.25.1, closes #5400
- @wordpress/date to v3.12.0, closes #5398
- @wordpress/data to v4.25.0, closes #5397
- @wordpress/compose to v3.22.0, closes #5396
- postcss-nested to v5, closes #5384
- @wordpress/scripts to v12.5.0, closes #5331
- @wordpress/plugins to v2.23.0, closes #5330
- postcss-import to v13, closes #5529
- @wordpress/e2e-test-utils to v4.15.0, closes #5328
- @wordpress/i18n to v3.16.0, closes #5187
- @wordpress/html-entities to v2.9.0,  closes #5186
- @wordpress/escape-html to v1.10.0, closes #5183
- @wordpress/element to v2.18.0, closes #5182
- @wordpress/dom-ready to v2.11.0, closes #5179
- @wordpress/blocks to v6.24.1, closes #5176
- @wordpress/babel-preset-default to v4.19.0, closes #5174
- @wordpress/api-fetch to v3.20.0, closes #5173
- puppeteer to v5, closes #4976
</details>

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by westonruter** [comment]
A build is failing with an error:

> TypeError: rule.use.find is not a function

**Comment by pierlon** [comment]
> A build is failing with an error:
> 
> > TypeError: rule.use.find is not a function

Should now be resolved in https://github.com/ampproject/amp-wp/pull/5554/commits/36fe2124f24b763b1f6f6b2d322ea1986f614d14.

**Review by westonruter — APPROVED** [review]
LGTM! Awaiting +1 from @johnwatkins0.

**Review by johnwatkins0 — APPROVED** [review]
Looks good

**Comment by westonruter** [comment]
@pierlon there appear to be conflicts which need resolving before I can merge this.

**Pull request closed without merging**
