### PR TITLE
Update Support Links

### PR DESCRIPTION
**Pull request by westonruter**
The endpoint where we were sending support data has been turned down so we need to eliminate the Support screen in favor of directing users directly to the support forum.

### CODE REVIEW

**Comment by westonruter** [comment]
Build for testing: [amp.zip](https://github.com/user-attachments/files/17624717/amp.zip)

**Review by milindmore22 — APPROVED** [review]
Tested LGTM 👍🏼

**Comment by thelovekesh** [comment]
Need to bust runner cache in order to fix static analysis. The error is false positive.

**Review by thelovekesh — APPROVED** [review]

**Comment by westonruter** [comment]
Hummm. Static analysis is still failing after the runner cache was busted.

**Comment by thelovekesh** [comment]
Seems like this bug is back with the version just released - https://github.com/phpstan/phpstan/releases/tag/2.0.1

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

The support screen has been removed. 

image

**Pull request merged**
