### PR TITLE
Hide recommendations when Site Scan results are stale on Settings screen

### LINKED ISSUE #6690: Hide recommendations when Site Scan results are stale
### Feature Description

If the Site Scan results are stale or the Site Scan is currently in progress, none of the Template Modes should have “Recommended” or “Not recommended” appear anywhere. These should only be shown if the Site Scan is complete and the results are not stale.

Additionally, it may make sense to hide the notice above the template modes since the Site Scan box already is indicating "Stale Results":

image

### Acceptance Criteria

_No response_

### Implementation Brief

_No response_

### QA Testing Instructions

_No response_

### Demo

_No response_

### Changelog Entry

_No response_

### PR DESCRIPTION
**Pull request by delawski**
## Summary

Fixes #6690

This PR updates the Template Mode recommendation logic:

- [x] Remove notice about stale scan results from the Template Mode section on the AMP Settings screen.
- [x] Do not show any recommendations when the scan results are stale of a scan is in progress.
- [x] _Optionally:_ Update recommendation descriptions/details (both in the [matrix](https://docs.google.com/document/d/1yjpVpGV6PCPs641hzmUWXzo0a46VKvjiWTytFqxtyEk/edit) and in the [code](https://github.com/ampproject/amp-wp/blob/792543f31c591fbde212f15f024182a3f2e9eaff/assets/src/components/use-template-mode-recommendation/index.js#L55-L69)).

The screenshot below presents a case when the scan results are stale. There is no stale results notice below the Template Mode heading and no recommendation bubbles next to each template mode:

Screenshot 2021-11-08 at 13 29 07

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by delawski** [comment]
> _Optionally:_ Update recommendation descriptions/details (both in the [matrix](https://docs.google.com/document/d/1yjpVpGV6PCPs641hzmUWXzo0a46VKvjiWTytFqxtyEk/edit) and in the [code](https://github.com/ampproject/amp-wp/blob/792543f31c591fbde212f15f024182a3f2e9eaff/assets/src/components/use-template-mode-recommendation/index.js#L55-L69)).

@westonruter @maitreyie-chavan I'm leaving the last action item open in case you feel like it's a good idea to update the recommendation copy right now. Other than that, this PR is ready for review.

**Comment by milindmore22** [comment]
This may not be related, I noticed some inconsistencies 

I activate the ColorMag theme, did a site rescan It show an Incompatibility issue with colorMag theme but recommend it as Standard Mode.

image

**Comment by delawski** [comment]
@milindmore22 Thanks for testing it out.

> This may not be related, I noticed some inconsistencies

It actually falls under the last action item from the description:

> Optionally: Update recommendation descriptions/details (both in the matrix and in the code).

According to the current version of the [recommendation matrix](https://docs.google.com/document/d/1yjpVpGV6PCPs641hzmUWXzo0a46VKvjiWTytFqxtyEk/edit), if there are only theme issues and a user is technical, the Standard mode is recommended. I think the entire matrix should be revisited so that we're sure the recommendations are correct.

**Comment by dhaval-parekh** [comment]
Changes in PR looks good to me for the first two points. 👍

**Review by dhaval-parekh — APPROVED** [review]

**Comment by westonruter** [comment]
I've updated the recommendation matrix in 817d023. The document is difficult to maintain as is the corresponding code, so I'm exclusively going off of the codebase now. I've extracted common strings into variables and then re-used them across the various scenarios.

When an AMP-incompatible theme is active:

User is technical | User is non-technical
------------------|------------------------
image | image

For technical users, Transitional should also perhaps be `NEUTRAL` here.

In these screenshots, I've expanded each of the drawers to show all of the copy. It is more copy than before, for sure, but before there was not enough and I was left wondering what a template mode was. So now the same description is present for each template mode regardless of the scenario, and then prose recommendations form the next bullet point(s).

**Review by westonruter — APPROVED** [review]

**Pull request merged**
