### PR TITLE
Eliminate `amphtml` link relation from AMP-to-AMP linking

### LINKED ISSUE #6599: Structured data broken by `amphtml` link relation in AMP-to-AMP linking
## Bug Description

In a recent [support topic](https://wordpress.org/support/topic/error-in-required-structured-data-element-51/), we found out that BreadCrumbList schema (RDFa) doesn't allow `rel="amphtml"` attributes and marks structured data as invalid, As per discussion on slack Weston suggested we don't need it.

Example HTML Snippet : 
```html
<div class="breadcrumb" typeof="BreadcrumbList" vocab="https://schema.org/">
	<span property="itemListElement" typeof="ListItem">
	    <a property="item" typeof="WebPage" title="Go to Visitor Guard®." href="https://www.example.com?amp" class="home" rel="amphtml">
	        <span property="name">
	            Home
	        </span>
	   </a>
	<meta property="position" content="1">
	</span>
	<span class="post post-page current-item">
	    The Page Title
	 </span>
</div>
```
Tests : 

1. [Invalid Test ](https://search.google.com/test/rich-results?id=cQnZu_lCE6bMUgEJ7JsMKA) 
2. [Valid Test ](https://search.google.com/test/rich-results?id=nlyaLWLFGcoWt3uIefvUZg)

## Expected Behaviour

The page links should be served without `"rel="amphtml"` attributes.

## Steps to reproduce

1. Install and activate BreadCrumb Navxt Plugin
2. Add Breadcrumb to your site
3. Check the Structured Data on https://search.google.com/test/rich-results

## Additional context

 - WordPress version: 5.8.1
 - Plugin version: 2.1.4
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Transional Mode / Reader Mode
 - PHP version: 7.4
 - OS: Mac
 - Browser: chrome, safari
 - Device: Macbook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by bartoszgadomski**
## Summary

Fixes #6599

The `amphtml` link relation is no longer added since it has served no purpose. Additionally, the `noamphtml` relation is no longer added to the mobile version switcher link.

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Review by westonruter — CHANGES_REQUESTED** [review]
I think this may be too conservative in its exclusion, by limiting it to only `WebPage`, which is just one subtype of `CreativeWork`. There are many others, like `AboutPage` or `AmpStory`. These also fail if there is a `rel` attribute present. So I think the check should rather be for whether there is a `property` attribute on the link, and if so, skip adding the `rel`. 

Or given that the `amphtml` link relation has served no purpose since we introduced it, we should just eliminate adding it altogether.

**Comment by bartoszgadomski** [comment]
Thanks @westonruter for your comment. What about the `rel=noamphtml`, does this have any purpose or can be removed as well?

**Comment by westonruter** [comment]
> What about the `rel=noamphtml`, does this have any purpose or can be removed as well?

Adding it doesn't really have a purpose, no. As a page author you can disable AMP-to-AMP linking for an individual link if you give it the `noamphtml` relation. But otherwise, there's not any known need to _add_ the relation when AMP-to-AMP is being excluded

**Review by westonruter — APPROVED** [review]

**Review by milindmore22 — APPROVED** [review]
Works as expected

**Comment by milindmore22** [comment]
**QA Passed**

**Input**
```html
<a rel="noreferrer noopener" href="https://amp-local.test/hello-world/" data-type="post" data-id="1" target="_blank">Internal Link to AMP Page – Should not have amphtml</a>
```
**Output**
```html
<a rel="noreferrer noopener" href="https://amp-local.test/hello-world/amp/" data-type="post" data-id="1" target="_blank">Internal Link to AMP Page – Should not have amphtml</a>
```

| Input | amphtml | nonamphtml | Link Type |
| ----------- | ----------- | ----------- | ----------- |
| Internal Link to AMP page | Removed | N/A | Link to AMP page |
| Internal Link to non-AMP Page | Removed | N/A | Link to AMP Page ( redirects to non-AMP ) |
| Internal Link with noamphtml attribute | Removed | Present | Link with nonamp=mobile parameter |
| External Link | Removed | N/A | No change |
| External Link with noamphtml attribute | Removed | Present | No change |

**Pull request merged**
