### PR TITLE
Rework displaying block validation messages.

### LINKED ISSUE #1679: Gutenberg lagging and high CPU usage when in paired mode
When AMP is in paired mode, there's massive lag when using Gutenberg demo post. I have tried this with twentyseventeen theme, and Gutenberg + AMP RC3 plugins active. The problem doesn't occur with default settings but only when paired mode is activated via functions.php:

```php
		// Add support 
		add_theme_support('amp', array(
			'paired' => true
		));
```

Screencast: https://d.pr/v/HLB3BN

### PR DESCRIPTION
**Pull request by miina**
Fixes #1679.

### CODE REVIEW

**Comment by kienstra** [comment]
# Before, In Paired Mode (Typing Is Slow)
typing-slow-gutenberg

# Before, In Classic Mode
typing-fast-gutenberg

# After, In Paired Mode (Typing Is Fast Again)
tpying-fast-amp-plugin-pr

**Comment by kienstra** [comment]
**Block-level Notices Still Appear**

block-level-notices-appear

**Comment by kienstra** [comment]
**Approved**

Hi @miina,
Thanks a lot for fixing this issue. This PR works locally, as shown in the `.gif` above.

**Comment by kienstra** [comment]
**Request For Review**

Hi @westonruter,
Could you please review this?

Also, here's a [test page](https://paired-ampconfdemo.pantheonsite.io/wp-admin/post.php?post=830&action=edit) on a staging site where the issue exists.

**Comment by westonruter** [comment]
Massive improvement to performance. Good work @miina!

**Pull request merged**
