### PR TITLE
Downgrade Composer to v1 in v2.0 of plugin

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

Reverts changes made in #5601.

Temporarily addresses #5609 until we find a robust solution for the issue.

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by westonruter** [comment]
Given that the automated build process in https://github.com/ampproject/amp-wp/pull/5610#issuecomment-730145407 is broken, here's a manual production build of this branch: 
[amp.zip](https://github.com/ampproject/amp-wp/files/5569278/amp.zip)

Diff from 2.0.6: https://gist.github.com/westonruter/6b6ad8c2bbccb30201e3df93263df712

**Comment by pierlon** [comment]
Automated builds are now working again.

**Review by westonruter — APPROVED** [review]
Approved pending testing in AMP Slack.

**Comment by westonruter** [comment]
Merging since Travis is taking its sweet time and the only changes reverts.

**Comment by westonruter** [comment]
Also, changes have been verified to no longer cause fatal errors.

**Pull request merged**
