### PR TITLE
Add PRs and issues from the 1.0 milestone to the changelog

### LINKED ISSUE #1108: Update changelog for v1.0 release [placeholder]
As we work we should track the progress of the plugin development. When appropriate, we should merge this in. 👍

### PR DESCRIPTION
**Pull request by kienstra**
**Request For Review**

Hi @westonruter,
Could you please review this update to the [Changelog](https://github.com/Automattic/amp-wp/blob/update/changelog-1.0-alpha/readme.md#10-unreleased)?
* Mainly lists PRs, except where there was extensive discussion on an issue.
* This is in reverse-chronological order, and it goes from the bottom up:
https://github.com/Automattic/amp-wp/milestone/7?closed=1
* It looks like that [v1.0 milestone](https://github.com/Automattic/amp-wp/milestone/7?closed=1) might have all of the closed PRs from the [v1.0 project](https://github.com/Automattic/amp-wp/projects/6). This [query](https://github.com/Automattic/amp-wp/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+no%3Amilestone+project%3AAutomattic%2Famp-wp%2F6+) for PRs in the [v1.0 project](https://github.com/Automattic/amp-wp/projects/6) that don't have a milestone doesn't show anything.
* The readme [description](https://github.com/Automattic/amp-wp/blob/3a0c575add40c41779c4fe3c0ab0df6446b92321/readme.md#description) still isn't upated for `1.0`. Maybe we could do that for the production release.

Closes #1108.

### CODE REVIEW

**Comment by westonruter** [comment]
@kienstra instead of sorting in reverse chronological order, could they be generally sorted by importance? What I have in mind is something similar to the “what's new” posts for Gutenberg, for example: https://make.wordpress.org/core/2018/05/18/whats-new-in-gutenberg-18th-may/

**Comment by kienstra** [comment]
Sounds good, @westonruter. I'll sort these by order of importance, like in the [Gutenberg post](https://make.wordpress.org/core/2018/05/18/whats-new-in-gutenberg-18th-may/) you mentioned.

**Comment by kienstra** [comment]
Hi @westonruter,
How does the updated [Changelog](https://github.com/Automattic/amp-wp/blob/update/changelog-1.0-alpha/readme.md#10-unreleased) look? My opinion of the relative importance is subjective 😄

**Comment by postphotos** [comment]
Hey @kienstra, this makes my job easier and looks better than before! Thanks for this! 🎆

**Pull request merged**
