### PR TITLE
Blacklists rev attribute

### PR DESCRIPTION
**Pull request by kraftbj**
Per the validator, `rev` is not a valid attribute. I don't see reference to this in the docs. As seen by using Jetpack's Markdown to create a footnote, which creates a link like `<a href="#fnref-3468-1" rev="footnote">↩</a>`

### CODE REVIEW

**Comment by mjangda** [comment]
Aside: should Jetpack switch to using `rel=footnote` instead?

**Comment by mjangda** [comment]
Also, is the `rev` only used with `a` tags? If so, might be better to only look for and strip from those tags, instead of all.

**Comment by kraftbj** [comment]
Looking closer, `rev` is only on `a` and now obsolete. HTML5 removed it from the spec. I'll dig in on the Jetpack side to determine the best attribute to use (I assume `rel`).

**Comment by kraftbj** [comment]
@mjangda What do you think about closing this since, technically, the problem is invalid HTML being provided by the site, not sanitizing valid HTML into AMP?

**Comment by kraftbj** [comment]
Via discussion on Slack, even if corrected in Jetpack, Jetpack's markdown would have saved the older HTML4 to the database until the next time the post is saved. It's would be better of us to remove it.

**Comment by mjangda** [comment]
:boom:

**Pull request merged**
