### PR TITLE
Remove empty scripts after webpack compilation

### LINKED ISSUE #6778: Empty JS files are generated as part of build
### Bug Description

Webpack is creating empty JS files when it is processing stylesheets:

image

These need to be omitted from the build, either by preventing them from being generated or by deleting them after running webpack.

### Expected Behaviour

No empty JS files should be created.

### Screenshots

_No response_

### PHP Version

_No response_

### Plugin Version

2.2

### AMP plugin template mode

Standard, Transitional, Reader

### WordPress Version

_No response_

### Site Health

_No response_

### Gutenberg Version

_No response_

### OS(s) Affected

_No response_

### Browser(s) Affected

_No response_

### Device(s) Affected

_No response_

### Acceptance Criteria

_No response_

### Implementation Brief

_No response_

### QA Testing Instructions

_No response_

### Demo

_No response_

### Changelog Entry

_No response_

### PR DESCRIPTION
**Pull request by delawski**
## Summary

Fixes #6778

So far, a custom `IgnoreExtraneousStyleAssets` webpack plugin has been used to prevent generation of empty JS files (e.g. when CSS has been an entry point). After updating webpack from version 4 to 5, the custom plugin stopped working due to webpack internal API changes.

It turns out there is a third-party plugin, [`webpack-remove-empty-scripts`](https://github.com/webdiscus/webpack-remove-empty-scripts) that does exactly what we need. It should be run before `DependencyExtractionWebpackPlugin` so that empty JS files are removed before `.asset.php` files are created.

Screenshot 2021-12-09 at 14 08 31

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by westonruter** [comment]
Here's a comparison before/after:

image

The empty files are all getting deleted as expected, except there's one interesting thing: [`amp-post-meta-box.js`](https://github.com/ampproject/amp-wp/blob/develop/assets/src/classic-editor/amp-post-meta-box.js) was empty before but now it is not empty. Was this broken before? It seems so! I just checked with the Classic Editor plugin active and there is an error:

> image

Clicking the “Edit” link for enabling AMP does nothing. Why was this file empty before?

Checking the same page with the changes in this PR shows shows no errors and the toggle is working:

> image

This file was not empty in 2.1.4, so something broke in `develop` between then and now which you are fixing here.

**Comment by westonruter** [comment]
Changes to `*.js` files between 2.1.4 and this PR:

image

All that looks right.

----

Changes to `*.asset.php` files:

image

This looks similarly right, _except_ for the `wp-components.asset.php` file. This file seems to still be generated incorrectly.

Or maybe not? Is it being generated for `wp-components.css` and we should actually be updating `register_shimmed_styles` to use the `version` in the assets file instead of the hard-coded `13.0.3` (which is probably wrong):

https://github.com/ampproject/amp-wp/blob/5ab441284a529c3c535e0145e1b869ecd2f3a03f/src/Admin/Polyfills.php#L164-L177

But if that is the case, then why is the `wp-components.asset.php` file in the `assets/js` directory and not the `assets/css` directory?

These are the changes to the `*.css` files between 2.1.4 and this PR:

image

**Comment by delawski** [comment]
> This looks similarly right, _except_ for the `wp-components.asset.php` file. This file seems to still be generated incorrectly.

I think it is the case. This file should not be generated since `wp-components.js` is bundled with the script files it is used on. The accompanying CSS file is, however, not manually imported to any of the JS entry points meaning we need to rely on Core exposing `wp-components.css` or polyfill it for older WP versions.

So far, `wp-components` has been added as one of the entry points in the `settingsPage` task. This resulted in a superfluous `wp-components.asset.php` file generation. With 544b66d we add `wp-components` stylesheet to the `styles` task, where it better fits. Also, thanks to that, no `.asset.php` file is created.

> Or maybe not? Is it being generated for `wp-components.css` and we should actually be updating `register_shimmed_styles` to use the `version` in the assets file instead of the hard-coded `13.0.3` (which is probably wrong):

I guess we can use the hard-coded value and update it anytime the `@wordpress/components` package is bumped (alternatively use the plugin version instead).

**Comment by westonruter** [comment]
> I guess we can use the hard-coded value and update it anytime the `@wordpress/components` package is bumped (alternatively use the plugin version instead).

Good idea. I've done that in 99a3a89a4.

**Comment by westonruter** [comment]
> So far, `wp-components` has been added as one of the entry points in the `settingsPage` task. This resulted in a superfluous `wp-components.asset.php` file generation. With [544b66d](https://github.com/ampproject/amp-wp/commit/544b66d8b7225e4a4d7540b334315efb30192d1f) we add `wp-components` stylesheet to the `styles` task, where it better fits. Also, thanks to that, no `.asset.php` file is created.

Perfect!

**Review by westonruter — APPROVED** [review]

**Pull request merged**
