### PR TITLE
Improve determination of eligible post types for AMP

### LINKED ISSUE #6883: Improve determination of eligible post types for AMP
### Feature Description

As noted in https://github.com/ampproject/amp-wp/pull/6881#issuecomment-1029267449:

> the only post types that are eligible for being AMP-enabled are those which have `'public' => true`:
> 
> https://github.com/ampproject/amp-wp/blob/36edf69661e8ee6c7c35bce1c483c9524dbf386f/includes/class-amp-post-type-support.php#L44-L64
> 
> It's true that a post type could have `public` set to true but have `publicly_queryable` set to false, I think, and in that case it may be possible that we could accidentally show or hide the preview button. It would be marginally better to here instead do the following since there is now a `is_post_type_viewable` filter in WP 5.9:
> 
> ```diff
> diff --git a/includes/class-amp-post-type-support.php b/includes/class-amp-post-type-support.php
> index 3d4560641..17eb6519b 100644
> --- a/includes/class-amp-post-type-support.php
> +++ b/includes/class-amp-post-type-support.php
> @@ -42,14 +42,9 @@ public static function get_builtin_supported_post_types() {
>  	 * @return string[] Post types eligible for AMP.
>  	 */
>  	public static function get_eligible_post_types() {
> -		$post_types = array_values(
> -			get_post_types(
> -				[
> -					'public' => true,
> -				],
> -				'names'
> -			)
> -		);
> +		$post_types = array_values( get_post_types( [], 'names' ) );
> +
> +		$post_types = array_filter( $post_types, 'is_post_type_viewable' );
>  
>  		/**
>  		 * Filters the list of post types which may be supported for AMP.
> ```

### Acceptance Criteria

Only post types for which `is_post_type_viewable()` returns `true` should be listed among the post types for which AMP can be enabled. Only these post types should have an AMP preview button shown in a paired AMP mode (transitional or reader).

### Implementation Brief

_No response_

### QA Testing Instructions

_No response_

### Demo

_No response_

### Changelog Entry

_No response_

### PR DESCRIPTION
**Pull request by dhaval-parekh**
## Summary

Fixes #6883 

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by westonruter** [comment]
Would you add a test case for when someone filters `is_post_type_viewable` to be `false`?

**Comment by dhaval-parekh** [comment]
> Would you add a test case for when someone filters `is_post_type_viewable` to be false?

I have added a test case when someone uses the `is_post_type_viewable` filter to be false.

**Review by westonruter — APPROVED** [review]

**Comment by dhaval-parekh** [comment]
**Steps for QA**

- Install and activate the [this](https://gist.github.com/dhaval-parekh/7c9f3d68d6e37e66314206ad0aceb15a) plugin. 
- The "Book" and "Car" post types are eligible to post types for AMP.  While "Secret", "Secret Book" and "Secret Car" are not eligible.

image

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Eligible post types for AMP are visible in Supported Templates section

Screenshot 2022-03-31 at 2 21 20 PM

**Pull request merged**
