### PR TITLE
Improve styling of Compatibility Tool pages

### PR DESCRIPTION
**Pull request by kienstra**
* Add more space between the list table and the filter and search box
* Vertically center the 'double-caret' in the 'Details' column
* Add space between 'Accept' and 'Reject' buttons.
* In expandable 'Details' section, add space between `<summary>` and div.detailed

### CODE REVIEW

**Comment by kienstra** [comment]
https://github.com/Automattic/amp-wp/pull/1462/commits/501f28f4470ce397758aa2e108e3e0d5be387421 makes these changes to the single error URL page (#1365):

single-error-styling

**Comment by kienstra** [comment]
https://github.com/Automattic/amp-wp/pull/1462/commits/7df5837898048c83200d3483ceedc41f3735bc78 widens the 'Error' column:
single-error-url-wider

**Comment by kienstra** [comment]
https://github.com/Automattic/amp-wp/pull/1462/commits/9fdd697e4f345e495b210e02f5de813fb12ee6da removes the `<code>` wrapper (with the gray background):
code-wrapper

**Comment by kienstra** [comment]
https://github.com/Automattic/amp-wp/pull/1462/commits/e69d2f1263f347f303c95a6e7c025dc46bfe4f45 adds `cursor: pointer` when hovering over the `<details>` in the 'Summary' column:
single-error-page-cursor-pointer

**Comment by kienstra** [comment]
https://github.com/Automattic/amp-wp/pull/1462/commits/c714c2172f80d7327d3e8a3b3d8c7ccefc8b9ce9 adds the 'divider' per the [design](https://sketch.cloud/s/xQRzx/all/page-1/amp-validation-errors-for-amp-test-embeds):

single-error-horizontal-divider

**Comment by kienstra** [comment]
https://github.com/Automattic/amp-wp/pull/1462/commits/22c654de981c97173c49dde15865123ef70a07c7 changes the 'Accepted' icon on the single error URL page to be the green checkmark, like on the AMP Validation Error Index page:

single-error-url-page

**Comment by kienstra** [comment]
https://github.com/Automattic/amp-wp/pull/1462/commits/b204f46af431101496010baffeba94aa50706923 reduces the space between these items in the 'Status' box:

less-space

**Comment by kienstra** [comment]
https://github.com/Automattic/amp-wp/pull/1462/commits/e4b00e7d7f8d43246d2675365ef9b0b0a8cbc4d3 uses a darker version of red for the 'Invalid' column, to improve accessibility:

different-color

**Comment by kienstra** [comment]
https://github.com/Automattic/amp-wp/pull/1462/commits/b07bdbe5306439c416af43c6ee1b4c94a3e89399 moves the dates filter to the right on the 'Invalid URLs' page and the single error term page:

dates-filter-moved

**Comment by kienstra** [comment]
Hi @westonruter, this is ready for review.

There still might be more styling changes much later today or tomorrow, but there's no reason this can't be reviewed now.

**Comment by westonruter** [comment]
@kienstra The code looks good. So let me know when it's ready to merge.

**Comment by kienstra** [comment]
Thanks, @westonruter. I think it's ready to merge now. 

Any changes much later today or tomorrow could be in a new PR.

**Pull request merged**
