### PR TITLE
Upgrade php-css-parser to v8.4.0

### PR DESCRIPTION
**Pull request by westonruter**
See [changelog for v8.4.0](https://github.com/sabberworm/PHP-CSS-Parser/blob/8.4.0/CHANGELOG.md#840).

PHP-CSS-Parser went a long time without a release. Version 8.3.0 was released 2019-02-22, and in order to deploy unreleased improvements we updated to include the commits we needed (https://github.com/ampproject/amp-wp/pull/4300, https://github.com/ampproject/amp-wp/pull/5081) in addition to applying additional patches (https://github.com/ampproject/amp-wp/pull/5392, https://github.com/ampproject/amp-wp/pull/4290, etc). 

Changes between v8.3.0 and what we released: https://github.com/sabberworm/PHP-CSS-Parser/compare/8.3.0...bfdd976
Changes between what we released and v8.4.0: https://github.com/sabberworm/PHP-CSS-Parser/compare/bfdd976...8.4.0

So this PR updates to the latest stable release as well as:

* Remove now-obsolete php-css-parser-install-composer-plugin.
* Bump stylesheet cache group.
* Update patches to address merge conflicts.

Additional patches on top of v8.4.0 are applied from these PRs:

* https://github.com/sabberworm/PHP-CSS-Parser/pull/350
* https://github.com/westonruter/PHP-CSS-Parser/pull/2
* https://github.com/westonruter/PHP-CSS-Parser/pull/1

### CODE REVIEW

**Review by dhaval-parekh — APPROVED** [review]
Changes looks good to me.

**Comment by westonruter** [comment]
Eesh. I just found that the patches fail to apply when running `composer install --prefer-dist` but they succeed when running `composer install --prefer-source`.

**Comment by westonruter** [comment]
Yeah, it's also [failing in the GHA build](https://github.com/ampproject/amp-wp/runs/4590845933?check_suite_focus=true#step:8:111):

```
  - Applying patches for sabberworm/php-css-parser
    https://github.com/sabberworm/PHP-CSS-Parser/compare/e41d2140031d533348b2192a83f02d8dd8a71d30...b1f74798a7d21d0e6f6402ee8a06c92c7f92fae5.diff (1. Add additional validation for size unit <https://github.com/sabberworm/PHP-CSS-Parser/pull/350>)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://github.com/sabberworm/PHP-CSS-Parser/compare/e41d2140031d533348b2192a83f02d8dd8a71d30...b1f74798a7d21d0e6f6402ee8a06c92c7f92fae5.diff
    https://github.com/westonruter/PHP-CSS-Parser/compare/e41d2140031d533348b2192a83f02d8dd8a71d30...a49bd92c35e9bbbaaca23cf33874a65dd485c30b.diff (2. Validate name-start code points for identifier <https://github.com/westonruter/PHP-CSS-Parser/pull/2>)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://github.com/westonruter/PHP-CSS-Parser/compare/e41d2140031d533348b2192a83f02d8dd8a71d30...a49bd92c35e9bbbaaca23cf33874a65dd485c30b.diff
    https://github.com/westonruter/PHP-CSS-Parser/compare/e41d2140031d533348b2192a83f02d8dd8a71d30...935ea79e0389e672a9deadf9f366e6faab9110ba.diff (3. Fix parsing CSS selectors which contain commas <https://github.com/westonruter/PHP-CSS-Parser/pull/1>)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://github.com/westonruter/PHP-CSS-Parser/compare/e41d2140031d533348b2192a83f02d8dd8a71d30...935ea79e0389e672a9deadf9f366e6faab9110ba.diff
```

I believe it's due to the patches including changes to `tests` which aren't included in dist.

**Comment by maitreyie-chavan** [comment]
@dhaval-parekh Please could you review this again further to the findings @westonruter shared and new changes pushed.

**Pull request merged**
