### PR TITLE
Serve legacy post template CSS as minified

### PR DESCRIPTION
**Pull request by paulschreiber**

### CODE REVIEW

**Comment by paulschreiber** [comment]
Should I open an issue for:
>we should output-buffer the CSS and then send it through the AMP_Style_Sanitizer do the minification. Or rather, the PHP-CSS-Parser can be used to do the minification without invoking the full sanitizer.

**Comment by westonruter** [comment]
If you want. Or you can use this PR for that purpose.

**Comment by westonruter** [comment]
Note that output-buffering and minifying the entire legacy post template CSS would then also include any CSS added via the `amp_post_template_css` action, not just the CSS coming from the AMP plugin (which you minified here).

**Comment by westonruter** [comment]
Closing for now since a different approach will be needed.

**Pull request closed without merging**
