### PR TITLE
Prevent query_string filters from blocking AMP display (Issue #391)

### PR DESCRIPTION
**Pull request by mkuplens**
Test for presence of 'query_string' filters and append AMP parameter to output to ensure the query_var is not lost.

### CODE REVIEW

**Comment by mjangda** [comment]
Thanks @mkuplens! Can you provide reproduction steps for the issue so I can confirm this does fix things? (I didn't see any in #391)

**Comment by mkuplens** [comment]
Activating a plugin that hooks into the 'query_string' filter will disable AMP output unless the amp parameter is given a value (?amp=1 or /amp/1).

Reproduce with this single-file plugin: http://cl.ly/gDiM

**Comment by mjangda** [comment]
Thanks. Confirmed the issue, although, how about this as an alternate fix (feels like this could prevent other future issues that might crop up with `query_vars`)?

```
// Make sure the `amp` query var has an explicit value.
// Avoids issues when filtering `query_string`.
add_filter( 'request', 'amp_force_query_var_value' );

function amp_force_query_var_value( $query_vars ) {
    if ( isset( $query_vars[ AMP_QUERY_VAR ] ) ) {
        $query_vars[ AMP_QUERY_VAR ] = 1;
    }
    return $query_vars;
}
```

**Comment by mjangda** [comment]
Continued in #408

**Pull request closed without merging**
