### PR TITLE
Remove unused NPM dependencies

### LINKED ISSUE #5636: Remove obsolete NPM dev dependencies
## Feature description

I think there are few dev dependencies in package.json that are not used directly in the plugin. Removing them would save dependabot work and may slightly improve build times. A little investigation might be needed to determine which are not being used. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Dependencies in package.json only contain what's needed.
* All scripts still work.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by johnwatkins0**
## Summary

Fixes #5636 

This removes several NPM dev dependencies that, from what I can tell, no longer need to be installed directly in the plugin. A few are not used at all, while several are provided via other dependencies that this plugin does use directly (e.g., webpack via @wordpress/scripts). Would be good to have you validate @westonruter @pierlon in case I'm missing some use for any of these, maybe in the deployment script.

This will reduce the number of dependabot PRs and may slightly improve build times.

## Checklist

- [X] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [X] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by pierlon** [comment]
**A summary of the removed dependencies:**

Unused direct dependencies:
- @babel/cli
- postcss-color-function
- svg-inline-loader
- travis-size-report

Direct dependencies that are provided via transitive dependencies:

Dependency | Provided by
---|---
babel-eslint | @wordpress/eslint-plugin
babel-jest | @wordpress/scripts
babel-loader | @wordpress/scripts
browserslist | @wordpress/scripts
core-js | @wordpress/babel-preset-default
css-loader | @wordpress/scripts
cssnano | optimize-css-assets-webpack-plugin
mini-css-extract-plugin | @wordpress/scripts
source-map-loader | @wordpress/scripts
uuid | @wordpress/blocks
webpack | @wordpress/scripts

---

@johnwatkins0 some additional dependencies that can be removed:

- autoprefixer (provided by @wordpress/scripts)
- postcss-loader (provided by @wordpress/scripts)
- rtlcss (seems to be unused; provided by rtlcss-webpack-plugin)

Also, these dependencies are provided by `@wordpress/scripts` but are currently incompatible with the versions provided by the package:
- puppeteer
- postcss

Once `@wordpress/scripts` supports `puppeteer` v5 and `postcss` v8 those direct dependencies can also be removed.

**Comment by johnwatkins0** [comment]
Thanks for the detail @pierlon. I removed those additional dependencies you mentioned with the exception of `postcss-loader`, whose removal broke the build script for some reason. I also restored `uuid` because it turns out I was mistaken and we are using it. I moved it from devDependencies to dependencies, though.

**Comment by pierlon** [comment]
We could also use this opportunity to move some `devDependecies` into the `dependencies` list. From what I see those would be:

- @wordpress/block-editor
- @wordpress/blocks
- @wordpress/components
- @wordpress/edit-post
- @wordpress/plugins
- lodash
- moment

Any additions/disagreements @johnwatkins0?

**Comment by johnwatkins0** [comment]
> We could also use this opportunity to move some `devDependecies` into the `dependencies` list.

@pierlon This is a good idea, but don't you think we could even just remove some of these? I think the only ones we definitely need to keep are `@wordpress/components` (because we bundle it for the settings screen) and any that are being used in unit tests (not sure which without looking closer). If for example `@wordpress/edit-post` is always loaded from core thanks to the DependencyExtraction webpack plugin and is not being used in any tests, is there a reason to have it in `package.json`? Editor autocompletion is one benefit I can think of. Maybe that's enough -- but in this case I think having the packages in devDependencies would make sense.

**Comment by johnwatkins0** [comment]
Actually, on closer look, I think most or all of these packages are needed for the Jest tests, but if we're not bundling them anywhere and only using them in tests, are they dependencies or devDependencies?

**Comment by pierlon** [comment]
> Actually, on closer look, I think most or all of these packages are needed for the Jest tests...

@johnwatkins0  Yea that's a good point there. With that in mind I'd say we can keep the dependencies I listen in https://github.com/ampproject/amp-wp/pull/5669#issuecomment-742738008 as `devDependencies` then.

**Review by pierlon — APPROVED** [review]
This looks good :+1:

**Comment by johnwatkins0** [comment]
I did move `@wordpress/components` into dependencies, though, since we bundle it for settings and the wizard (41b44569e)

**Review by westonruter — APPROVED** [review]
I installed this on a test site and didn't notice any regressions.

**Pull request merged**
