### PR TITLE
AMP_Sanitizer

### PR DESCRIPTION
**Pull request by j3j5**
Load content from posts on UTF8 instead of default encoding.

### CODE REVIEW

**Comment by j3j5** [comment]
PR to fix #88

**Comment by j3j5** [comment]
Travis fails with `The command "bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION" failed and exited with 1 during .` but I don't think my commit breaks that script, any idea what could that be?

**Comment by mjangda** [comment]
Thanks @j3j5! Can you share some sample text/content that this fixes?

**Comment by j3j5** [comment]
Cool, I was going to reply now, anything UTF-8 using, for example `'` breaks into `â`.

**Pull request merged**
