### PR TITLE
Set php and js coverage threshold to 0.1%

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

Bumps the coverage threshold for the `php` and `js` projects from 0% to 0.1%

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by pierlon** [comment]
Would love to get @schlessera's feedback on this to see if we would be shooting ourselves in the foot with this change.

**Comment by schlessera** [comment]
@pierlon I might be missing something here: It looks from the diff like you're overriding the default `threshold: 0.1%` with language-specific settings of that very same threshold... ?

**Comment by pierlon** [comment]
@schlessera the Codecov docs gives the impression that the default threshold is applied to the language-specific settings, but in practice that has turned out to be false. We've been having PR checks fail even when the threshold is below the expected 0.1%.

To verify this I forked the project and tested my hypothesis. As you can see in https://github.com/pierlon/amp-wp/pull/3, at https://github.com/pierlon/amp-wp/pull/3/commits/424ddda0476fa33a15b6578dab7b609ffe0417ee the codecov php test failed when it decreased by 0.01%. When I set the threshold to 0.1% for php in https://github.com/pierlon/amp-wp/pull/3/commits/384e22424de2948ac552157357f3e27e0e0e3484, the coverage test passed.

**Comment by schlessera** [comment]
Alright. I do think that looks like a bug in CodeCov, it does not make full sense the way I read the configs.

**Review by schlessera — APPROVED** [review]
Let's try and see how this goes. Right now, I think our code coverage is a bit flaky overall because it use `pcov`, which seems to have trouble flagging everything it should...

**Pull request merged**
