### PR TITLE
Improve PHP 8.4 compatibility

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

This addresses all deprecation warnings on PHP 8.4, unblocking PHP 8.4 compatibility in the Web Stories plugin.

The handful of PHPStan failures are unrelated and can be addressed separately.

There are some test failures too but they can be handled separately as well.

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by westonruter** [comment]
Regarding the PHPStan issues, see also #7876.

**Comment by westonruter** [comment]
@thelovekesh Could you address the remaining PHPStan issues?

**Comment by westonruter** [comment]
As part of this, we should also update PHP-CSS-Parser which was just updated to improve PHP 8.4 compatibility: https://github.com/MyIntervals/PHP-CSS-Parser/releases/tag/v8.7.0

**Comment by swissspidy** [comment]
Might be a bigger change that warrants its own PR, as I assume the package‘s namespace changed as well and all those parches don‘t apply anymore

**Comment by westonruter** [comment]
The remaining error is due to a change in PHP 8.4 for the string representation of a closure. Should be a trivial fix.

**Comment by swissspidy** [comment]
I'll defer that to you then 😃

**Comment by westonruter** [comment]
Oof. That was more of a headache than I was expecting! Really confused why I needed to do d1e4a50 now just for PHP 8.4 although it also is failing for me locally in PHP 8.3. It should have been failing for all PHP versions.

**Review by westonruter — APPROVED** [review]

**Pull request merged**
