### PR TITLE
Don't show comment link if closed and no comments

### PR DESCRIPTION
**Pull request by mjangda**
See #516

h/t neotrope

### CODE REVIEW

**Comment by neotrope** [comment]
Hm. Seemed to get 500 error with all three lines, 

or with just these two
```
$comments_link_url = get_comments_link( $this->ID );
$comments_link_text = $comments_open
```

**Comment by allancole** [comment]
This seems to working without error for me, @mjangda but curious what error neotrope is getting.

**Comment by neotrope** [comment]
Sorry, all - got sidetracked on the OTHER thing I'm working on which is importing 12 years of content from custom CMS we built in 2004 into WordPress, and got stuck on a PHP function to rewrite category IDs from old fields to new category IDs (ouch!). Have not had a spare moment to attempt to test the fix again. Only got a 500 error; did not have WP debug on for more explicit info. SORRY!!

**Comment by mjangda** [comment]
@neotrope no worries. I haven't been able to reproduce the 500 and I've tested across a few different environments. If you do manage to catch the error again, feel free to re-open this.

**Comment by neotrope** [comment]
If you push a 0.41 in the next week, I'll revisit then and not bother you on this one :-)

**Pull request merged**
