### PR TITLE
Extend WordPress.tv embed handler to also handle VideoPress

### LINKED ISSUE #4754: Embedding VideoPress video causes validation error
## Bug Description

When embedding a VideoPress video such as https://videopress.com/v/kUJmAcSf in a VideoPress block, the result is a validation error:

image

The fix for this was partially implemented in #3542 because WordPress.tv also uses VideoPress architecture. So it just needs to be extended.

## Expected Behaviour

No validation error should be raised when embedding videos from VideoPress.

## Steps to reproduce

1. Enable Standard mode.
2. Embed a VideoPress block with the URL https://videopress.com/v/kUJmAcSf
3. Save draft
4. See validation error

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

Fixes #4754.

WordPress.tv uses the VideoPress infrastructure. However, we were only directly supporting WordPress.tv but not embeds from VideoPress itself. This fixes that. Note that both WordPress.tv and VideoPress are blocks that core supports.

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by pierlon** [comment]
I'll have to account for this in #4650.

**Comment by pierlon** [comment]
Actually, the solution that I have does unintentionally fix this bug. Would you still consider having this merged?

**Comment by westonruter** [comment]
We can defer to your solution instead.

**Comment by westonruter** [comment]
Or rather, rebase this exclusively to the 1.5 branch perhaps.

**Comment by pierlon** [comment]
Yes, that'd make sense.

**Review by pierlon — APPROVED** [review]

**Comment by westonruter** [comment]
@pierlon This PR has exposed that builds in the 1.5 branch are failing and have been failing:

image

Could you investigate and fix?

**Comment by pierlon** [comment]
Sure I'll see what the problem is.

**Comment by pierlon** [comment]
@googlebot I consent.

**Comment by pierlon** [comment]
@westonruter All seems well now. I've backported some fixes from the `develop` branch to fix the errors here.

**Comment by westonruter** [comment]
Thank you very much for wrestling with this one.

**Pull request merged**
