### PR TITLE
Update Gutenberg packages after v11.2.1 release

### PR DESCRIPTION
**Pull request by pierlon**

### CODE REVIEW

**Review by westonruter — APPROVED** [review]

**Comment by westonruter** [comment]
Oh, you should now be able to revert ~https://github.com/ampproject/amp-wp/pull/6464~ **#6476**.

**Comment by pierlon** [comment]
Turns out the React version mismatch was due to an outdated `package-lock.json`. Removing it and re-locking the dependencies resolved the issue (see https://github.com/ampproject/amp-wp/pull/6511/commits/a112bf979e254c6ae0e0ccecd9b7b55deb020df5).

**Comment by pierlon** [comment]
> Oh, you should now be able to revert #6464.

@westonruter How so? I'm not sure what you mean.

**Comment by westonruter** [comment]
> How so? I'm not sure what you mean.

Oops. I meant #6476! Because Gutenberg 11.2.0 fixed the PWA manifest icon issue (https://github.com/WordPress/gutenberg/pull/33702).

**Review by westonruter — APPROVED** [review]
Thank you for doing this.

**Pull request merged**
