### PR TITLE
Always download latest version of PHPStan

### LINKED ISSUE #4745: PHPStan is not automatically using the latest version to run its tests
## Bug Description

We currently download a fixed version of PHPStan. As this is not being caught by Dependabot, it means that we're never really using the best possible version of PHPStan.

We should instead download the latest version at all times, and this will then properly update issues as PHPStan gets smarter with each release.

Note:
This will add the following new issues with the latest version of PHPStan, so we'll need to fix these as well:
```
------ -------------------------------------------------------------------- 
  Line   includes/class-amp-theme-support.php                                
 ------ -------------------------------------------------------------------- 
  1614   Multiple PHPDoc @var tags above single variable assignment are not  
         supported.                                                          
 ------ -------------------------------------------------------------------- 
 ------ ----------------------------------------------------------------------- 
  Line   includes/sanitizers/class-amp-link-sanitizer.php                       
 ------ ----------------------------------------------------------------------- 
  140    Variable $element in PHPDoc tag @var does not match assigned variable  
         $admin_bar_container.                                                  
 ------ ----------------------------------------------------------------------- 
```

## Expected Behaviour

PHPStan should always run at the latest version within Travis CI.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by schlessera**
## Summary

Quick fix to adapt the URL to use for downloading PHPStan, as it makes more sense to always run against its latest version.

Fixes #4745

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Review by westonruter — APPROVED** [review]

**Review by westonruter — CHANGES_REQUESTED** [review]
This update has exposed other issues: https://travis-ci.org/github/ampproject/amp-wp/jobs/687969411#L541-L553

```
------ -------------------------------------------------------------------- 
  Line   includes/class-amp-theme-support.php                                
 ------ -------------------------------------------------------------------- 
  1614   Multiple PHPDoc @var tags above single variable assignment are not  
         supported.                                                          
 ------ -------------------------------------------------------------------- 
 ------ ----------------------------------------------------------------------- 
  Line   includes/sanitizers/class-amp-link-sanitizer.php                       
 ------ ----------------------------------------------------------------------- 
  140    Variable $element in PHPDoc tag @var does not match assigned variable  
         $admin_bar_container.                                                  
 ------ ----------------------------------------------------------------------- 
```

**Comment by schlessera** [comment]
Ah, I'll open an issue first and then fix this.

**Comment by schlessera** [comment]
Not really sure what is going on here for now, but I'm getting different results in Travis than on my local system:

Image 2020-05-19 at 12 42 58 PM

In the above screenshot, I'm testing the exact same code with the exact same version of PHPStan.

**Comment by schlessera** [comment]
Ok, on Travis, PHPStan seems to interpret blank lines differently than on my local machine.

Let's take the second issue above as an example.

Here's the relevant code:
```php
132	public function process_links() {
133		/**
134		 * Element.
135		 *
136		 * @var DOMElement $element
137		 */
138
139		// Remove admin bar from DOM to prevent mutating it.
140		$admin_bar_container   = $this->dom->getElementById( 'wpadminbar' );
```

This passes on my local machine, but throws the following issue on Travis:
```
 140    Variable $element in PHPDoc tag @var does not match assigned variable  
        $admin_bar_container.   
```

The issue does not make much sense, as the docblock is not directly attached to the variable, and shouldn't therefore affect how that variable is interpreted. It is qualifying `$element`, not `$admin_bar_container`.

However, if on my local machine I delete line 138 (the blank line), I get the following issue:
```
139    Variable $element in PHPDoc tag @var does not match assigned variable
       $admin_bar_container.
```

Note that removing the blank line attached the docblock to the `$admin_bar_container` now. Note also that the line number for the issue is `139`, not `140`.


So it seems that PHPStan has different behavior depending on the environment it is being run on.

**Comment by schlessera** [comment]
I adapted the docblocks so that hopefully PHPStan will pass now.

@westonruter, I'd love it if we can disable the PHPCS rule that forces us to create large multine docblocks. I'd prefer for these type-hinting docblocks to just be:
```php
/** @var DOMElement $element */
```
The rest is just noise in my opinion.

**Comment by westonruter** [comment]
> I'd love it if we can disable the PHPCS rule that forces us to create large multine docblocks

Agreed. I'm happy to allow single-line docblocks.

**Review by westonruter — APPROVED** [review]

**Comment by schlessera** [comment]
> Agreed. I'm happy to allow single-line docblocks.

Opened an issue for that: https://github.com/ampproject/amp-wp/issues/4756

**Pull request merged**
