### PR TITLE
Update how Imgur IDs are parsed

### LINKED ISSUE #4697: Imgur post embed gives 404 error
## Bug Description

The Imgur post embed generates AMP tag, it uses post id as data-imgur-id, and it creates incorrect embed URL: `https://imgur.com/2q6AS6i/embed?pub` so it’s not displayed on the AMP page.

```html
<amp-imgur
    data-imgur-id="2q6AS6i"
    layout="responsive"
    width="540"
    height="633"
  >
  </amp-imgur>

```
In the official AMP documentation, there is no information available for Imgur post embed.
https://amp.dev/documentation/components/amp-imgur/

And there is a merged PR to add the support for Imgur posts:
https://github.com/ampproject/amphtml/pull/23829

## Expected Behaviour

The Imgur post embed should generate `data-imgur-id` as `a/<post_id>`. It generates the correct embed URL `https://imgur.com/a/2q6AS6i/embed?pub`.

```html
<amp-imgur
    data-imgur-id="a/2q6AS6i"
    layout="responsive"
    width="540"
    height="633"
  >
  </amp-imgur>

```

## Steps to reproduce

1. Edit/Create WordPress post.
2. Add an Imgur post URL. eg. https://imgur.com/gallery/2q6AS6i
3. Submit the post.
4. View it on AMP mode

## Screenshots

C3r0URGdKN

## Additional context

 - WordPress version: 5.4
 - Plugin version: 1.5.3
 - AMP plugin template mode: Standad
 - PHP version: 7.4
 - OS: Windows 10
 - Browser: Google Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### LINKED ISSUE #5482: [amp-imgur] Some Imgur urls are not supported by AMP-WP plugin
## Bug Description

AMP WP plugin doesn't account for urls like this one:
https://imgur.com/a/rAG6Q2w

## Expected Behaviour
Account for https://imgur.com/a/{imgur_id} Imgur url format.

How about just replacing:
```
if ( ! isset( $pieces[1] ) ) {
```
with:
```
if ( ! isset( $pieces[1] ) ) {
	$pieces     = explode( '/a/', $parsed_url['path'] );
}
if ( ! isset( $pieces[1] ) ) {
```
in this method:
https://github.com/ampproject/amp-wp/blob/develop/includes/embeds/class-amp-imgur-embed-handler.php#L134

## Steps to reproduce

1. Embed https://imgur.com/a/rAG6Q2w 
2. Go to AMP version of the page

## Additional context

 - WordPress version: Any
 - Plugin version: 2.0.4
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

Fixes #5482
Fixes #4697

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by pierlon** [comment]
This PR is in counterpart with https://github.com/ampproject/amphtml/pull/30589 that fixes how singular Imgur IDs are sanitized. Currently embedding a Imgur gallery or album works fine, but if embedding a singular Imgur image, `amp-imgur` prepends the Imgur ID with `a/`, which results in a 404 when loading the embed.

**Comment by westonruter** [comment]
So is #4697 valid? Instead of:

```html
<amp-imgur
    data-imgur-id="2q6AS6i"
    layout="responsive"
    width="540"
    height="633"
  >
  </amp-imgur>
```

Should they have provided:

```html
<amp-imgur
    data-imgur-id="a/2q6AS6i"
    layout="responsive"
    width="540"
    height="633"
  >
  </amp-imgur>
```

?

**Comment by pierlon** [comment]
I would say it still is valid. Based on the reproduction steps provided the URL in question was https://imgur.com/gallery/2q6AS6i, which when previously parsed the ID would be `2q6AS6i`. The iframe URL would then be https://imgur.com/2q6AS6i, instead of the expected https://imgur.com/a/2q6AS6i.

**Comment by westonruter** [comment]
I'm seeing the `amp-imgur` getting a width of 580 and a height of 870:

Screen Shot 2020-10-09 at 13 12 47

This is coming from the `$attr` which is passed into `AMP_Imgur_Embed_Handler::filter_embed_oembed_html()`, which is coming from the initial oEmbed response data:

```json
{
    "version": "1.0",
    "type": "rich",
    "provider_name": "Imgur",
    "provider_url": "https://imgur.com",
    "width": 580,
    "height": 870,
    "html": "<blockquote class=\"imgur-embed-pub\" lang=\"en\" data-id=\"a/rAG6Q2w\"><a href=\"https://imgur.com/a/rAG6Q2w\">View post on imgur.com</a></blockquote><script async src=\"//s.imgur.com/min/embed.js\" charset=\"utf-8\"></script>"
}
```

There is no `width` or `height` in the actual `html`, even though it's attempting to parse it out. Is this dead code? 

https://github.com/ampproject/amp-wp/blob/5e85cc8665c7d19441d796f4112015a93742e00f/includes/embeds/class-amp-imgur-embed-handler.php#L52-L68

**Comment by westonruter** [comment]
The `width` and `height` issue appears to be specific to https://imgur.com/a/rAG6Q2w

**Comment by westonruter** [comment]
The excessive height seems to be a bug with Imgur's data response.

Nevertheless, should we be parsing the `width` and `height` when there is nothing in the HTML?

**Comment by pierlon** [comment]
Yea it does seem to be dead code. I'll remove it.

**Comment by westonruter** [comment]
Rebasing onto `develop` to fix build failure.

**Comment by westonruter** [comment]
> I would say it still is valid. Based on the reproduction steps provided the URL in question was https://imgur.com/gallery/2q6AS6i, which when previously parsed the ID would be `2q6AS6i`. The iframe URL would then be https://imgur.com/2q6AS6i, instead of the expected https://imgur.com/a/2q6AS6i.

But https://imgur.com/2q6AS6i/embed?pub=true is a failure whereas https://imgur.com/a/2q6AS6i/embed?pub=true succeeds. 

So then with the reversion of https://github.com/ampproject/amphtml/pull/30589 wouldn't this be required?

```html
<amp-imgur
    data-imgur-id="a/2q6AS6i"
    layout="responsive"
    width="540"
    height="633"
  >
  </amp-imgur>
```

**Comment by westonruter** [comment]
Wait, so this is the case actually. In https://github.com/ampproject/amp-wp/issues/4697 the issue was for embedding https://imgur.com/gallery/2q6AS6i.

Before this PR it was generating (which currently works until https://github.com/ampproject/amphtml/pull/30589 is merged):

```html
<amp-imgur width="580" height="870" data-imgur-id="2q6AS6i" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:580px;height:870px;" i-amphtml-layout="fixed"></amp-imgur>
```

Whereas with this PR, the result is:

```html
<amp-imgur width="580" height="870" data-imgur-id="a/2q6AS6i" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:580px;height:870px;" i-amphtml-layout="fixed"></amp-imgur>
```

The explicit `a/` here will ensure that https://imgur.com/a/2q6AS6i/embed?pub=true is the result.

**Review by westonruter — APPROVED** [review]

**Pull request merged**
