### PR TITLE
Fixes for allowing forms in AMP

### PR DESCRIPTION
**Pull request by stephywells**
This PR fixes a couple of issues with allowed tags for forms. The form validation needs these changes in order to validate and show error messages.

### CODE REVIEW

**Comment by stephywells** [comment]
Thanks for the update!

**Comment by Prozpe** [comment]
Strange problems on http://semtix.cz using AMP forms... not working at all, turning AMP support off now

**Comment by mjangda** [comment]
Thanks @stephywells; sorry for taking so long to merge!

**Comment by stephywells** [comment]
Thanks so much for merging this! Now I'll be able to release and addon for Formidable Forms.

**Pull request merged**
