### PR TITLE
Fix prod build for CI on 2.0 branch

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

This fixes the [recent build failure](https://github.com/ampproject/amp-wp/runs/2054447761#step:11:424) of the production build CI job on the 2.0 branch.

The cause was due to a composer requirement mismatch, where the `wp-cli/wp-cli` package was locked to the version `dev-master` (instead of adhering to the constraint `^2.4`), which then required newer versions of packages that conflicts with our set of version requirements:

```
  Problem 1
    - wp-cli/wp-cli-tests v3.0.9 requires dealerdirect/phpcodesniffer-composer-installer ^0.4.3 || ^0.5 || ^0.6.2 || ^0.7.1 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.4.3, v0.4.4, v0.5.0, v0.6.2, v0.7.1] but these conflict with your requirements or minimum-stability.
    - wp-cli/wp-cli-tests v3.0.8 requires dealerdirect/phpcodesniffer-composer-installer ^0.4.3 || ^0.5 || ^0.6.2 || ^0.7.1 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.4.3, v0.4.4, v0.5.0, v0.6.2, v0.7.1] but these conflict with your requirements or minimum-stability.
    - wp-cli/wp-cli-tests v3.0.7 requires dealerdirect/phpcodesniffer-composer-installer ^0.4.3 || ^0.5 || ^0.6.2 || ^0.7.1 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.4.3, v0.4.4, v0.5.0, v0.6.2, v0.7.1] but these conflict with your requirements or minimum-stability.
    - wp-cli/wp-cli 2.5.x-dev requires wp-cli/wp-cli-tests ^3.0.7 -> satisfiable by wp-cli/wp-cli-tests[v3.0.7, v3.0.8, v3.0.9].
    - Installation request for wp-cli/wp-cli (locked at 2.5.x-dev, required as ^2.4) -> satisfiable by wp-cli/wp-cli[2.5.x-dev].
```

The solution would be to update `composer.lock` to set the correct stable version of `wp-cli/wp-cli` to install.

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by pierlon** [comment]
I noticed `wp-cli/wp-cli` is also [locked to `dev-master`](https://github.com/ampproject/amp-wp/blob/d38eb952f4bb109f32b21ef2785dddf428c79395/composer.lock#L4135) on the `develop` branch, so that needs to be updated as well.

**Review by westonruter — APPROVED** [review]
Thank you for getting down to the issue.

**Comment by westonruter** [comment]
QA passed. Builds now succeed:

image

**Comment by pierlon** [comment]
> I noticed wp-cli/wp-cli is also locked to dev-master on the develop branch, so that needs to be updated as well.

Or maybe not... Since the `minimum-stability` is set to `dev`, the `dev-master` version of `wp-cli/wp-cli` would be the most acceptable version, but since `prefer-stable` is set to `true` I would think `v2.4.1` would be the version to lock.

Do you have any insights @schlessera?

**Pull request merged**
