### PR TITLE
[2.1]  Add Composer plugin to correctly autoload PHP CSS Parser dependency

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

Backport of #6464.

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Review by westonruter — APPROVED** [review]

**Comment by pierlon** [comment]
I've traced the E2E JS test failures to the latest Gutenberg release (v11.1.0). Whenever a test navigates to the Onboarding Wizard screen the Gutenberg plugin throws an error on the page because the admin bar is not present on the page, which causes puppeteer to lose its mind and bail for some reason. I've filed an issue on their repo (see https://github.com/WordPress/gutenberg/issues/33591) to see how best that can be resolved.

In the interim I think we can temporarily fix these E2E tests by using and pinning the last Gutenberg release (v11.0.0), as it won't throw the error.

Also note this affects the `develop` branch as well.

**Comment by pierlon** [comment]
> Also note this affects the develop branch as well.

Weirdly puppeteer doesn't bail and runs all tests to completion, although it does emit [similar errors](https://github.com/ampproject/amp-wp/runs/3122166206#step:14:14):

image

That's most likely due to the `develop` branch using a much more recent version of puppeteer.

**Comment by westonruter** [comment]
> Also note this affects the `develop` branch as well.

Will you open a PR to do this for `develop` as well?

**Comment by pierlon** [comment]
Yep sure.

**Comment by westonruter** [comment]
**QA Passed**

In the 2.1 branch, the `autoload` path is:

https://github.com/ampproject/amp-wp/blob/4205e6e5a31cc375023a40e18ece04b4e23321e2/composer.lock#L202-L212

This corresponds with https://github.com/ampproject/amp-wp/pull/6464#issuecomment-883747974.

**Pull request merged**
