### PR TITLE
Add RewriteAmpUrls transformer

### LINKED ISSUE #20: Extend Optimizer with transformer for module/nomodule scripts (ESM)
## Feature description

See https://github.com/ampproject/amp-toolbox/pull/722.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### LINKED ISSUE #4589: Add support for LTS releases in the RuntimeCSS Transformer
## Feature description

LTS releases of the runtime can now be requested from the AMP CDN.

The Optimizer transformer that fetches the AMP runtime CSS to inline should be adapted to support this.

See https://github.com/ampproject/amp-toolbox/commit/b154a73c6dc9231e4060434c562a90d983e2a46d

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Transformer configuration allows for an LTS runtime version to be requested for inlining the CSS.

## Implementation brief

* Align to the implementation of the NodeJS version: https://github.com/ampproject/amp-toolbox/commit/b154a73c6dc9231e4060434c562a90d983e2a46d

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### LINKED ISSUE #4600: Integrate support for AMP release channels
## Feature description

Follow-up on #4390.

AMP has a new LTS channel in addition to Beta and Experimental channels. The LTS channel gets a dedicated URL while the Beta and Experimental channels are per user opt-in via cookie. Cookie-based opt-in however conflicts with the needs of serving AMP pages via service worker since it means those scripts must be cached by the service worker as `opaque`, meaning that they could consume much more of a site's storage budget than than they would if they had been served with `crossorigin=anonymous`. See https://github.com/ampproject/amphtml/issues/24731 and https://github.com/ampproject/amphtml/issues/27267.

The AMP plugin therefore should transition to adding `crossorigin=anonymous` to all scripts (and styles) that it adds to the page. This has an additional benefit of providing more guarantees for user privacy. (Ultimately this won't be necessary once self-hosting of AMP scripts is available per #4530). 

_**Update:** With the landing of ESM scripts, `crossorigin=anonymous` is now added to all scripts by the AMP Optimizer._

Once this is done, we then will also need an alternative to using cookies for sites to opt-in to non-stable release channel(s). In addition to LTS, there is now a way to reference the `experimental` and `beta` channels via a new `optin` query param: https://github.com/ampproject/amphtml/pull/27587. These scripts will not be valid AMP, so when a non-stable release channel is chosen then the document must be put into dev mode.

The way to opt-in to a release channel can be accomplished via a filter like `amp_release_channel` which would take one string argument that can be modified by callbacks to be one of:

* `'stable'` (default)
* `'lts'`
* `'beta'`
* `'experimental'`

A special value of `false` should also be considered to revert to the current behavior where stable releases are used with _no_ `crossorigin=anonymous` being added, which will allow for cookies to be used to control the AMP version.

Note that the Optimizer also needs to add support for LTS channel. See https://github.com/ampproject/amp-wp/issues/4589 and https://github.com/ampproject/amp-toolbox/pull/691.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

1. Add new `amp_release_channel` filter.
2. Adjust generation of script URLs based on filtered value.
3. Adjust recognition of scripts to account for different values.
4. Add `crossorigin=anonymous` to all scripts.
5. Add dev mode to scripts when the beta or experimental channels are being used. 
6. Add support for LTS releases in the RuntimeCSS Transformer. See #4589.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### LINKED ISSUE #4607: Extend Optimizer with transformer for module/nomodule scripts
## Feature description

See https://github.com/ampproject/amp-toolbox/pull/722.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by schlessera**
## Summary

Adds the `RewriteAmpUrls` transformer.

This is used for switching URLs to an AMP LTS channel or for adding ESM support when loading the runtime and components.

Fixes https://github.com/ampproject/amp-toolbox-php/issues/20
Fixes #4600

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by schlessera** [comment]
I found out why all the tests succeed, while it doesn't seem to do anything on the actual site:
The scripts to load AMP components are not yet part of either the sanitizer or the optimizer, they are added in `AMP_Theme_Support::ensure_required_markup()`, which is running immediately _after_ the Optimizer.

The quick fix would be to move it _before_ the Optimizer. However, the proper fix would be to add automatic extension resolution to either the Sanitizer or the Optimizer.

Note: The Node.JS Optimizer has a transformer for this: https://github.com/ampproject/amp-toolbox/blob/master/packages/optimizer/lib/transformers/AutoExtensionImporter.js

**Comment by schlessera** [comment]
### Preliminary testing

Without ESM:

Image 2020-07-24 at 12 41 29 PM

Image 2020-07-24 at 12 42 37 PM

With ESM:

Image 2020-07-24 at 12 41 58 PM

Image 2020-07-24 at 12 39 25 PM

The difference is not huge but impactful nevertheless.

I assume that this will further improve as the ESM tooling for `amphtml` will be further refined.

The implementation currently causes the following AMP validation issues:
* `The attribute 'nomodule' may not appear in tag 'amphtml engine v0.js script'.` (1x for the runtime)
For each extension:
* `The attribute 'src' in tag '<extension> extension .js script' is set to the invalid value 'https://cdn.ampproject.org/v0/<extension>-0.1.mjs'.`
* `The attribute 'type' in tag '<extension> extension .js script' is set to the invalid value 'module'.`
* `Custom JavaScript is not allowed.` (=> AMP extension script is not recognized with .mjs file extension, so tagged as custom JS)

Note that the plugin's validation does pass successfully, as we have a chicken&egg problem, due to the fact that the sanitizer & validator are the same thing. The Optimizer would conceptually need to run after the sanitizer but before the validator. As it is now, it runs after both of these, as they can't be separated. Therefore, any validation issues that the Optimizer introduces won't be caught if they would be detected by a sanitizer like the `AMP_Tag_And_Attribute_Sanitizer`.

**Comment by westonruter** [comment]
> Note that the plugin's validation does pass successfully, as we have a chicken&egg problem, due to the fact that the sanitizer & validator are the same thing. The Optimizer would conceptually need to run after the sanitizer but before the validator. As it is now, it runs after both of these, as they can't be separated. Therefore, any validation issues that the Optimizer introduces won't be caught if they would be detected by a sanitizer like the `AMP_Tag_And_Attribute_Sanitizer`.

Yes, I think we need to basically promise that the the Optimizer's transformers are not going to cause invalid output. That's the current state of things. Also, the `AMP_Tag_And_Attribute_Sanitizer` is explicitly only accepting non-`transformed` markup anyway. The spec importer will omit any rule that relates to `transformed`. If we rearrange things to run the `AMP_Tag_And_Attribute_Sanitizer` after the Optimizer, then it would have to learn how to handle `transformed` input. We should probably do that eventually, but that will be a big effort.

**Comment by schlessera** [comment]
This PR needs to be transferred over to https://github.com/ampproject/amp-toolbox-php/.

**Comment by erwinmombay** [comment]
howdy, all. The validator should now allow these transformations to be valid. Is there a way for us to test this out?

**Comment by westonruter** [comment]
@erwinmombay This PR is stale and needs to be re-started on the amp-toolbox-php repo, so it's not really in a testable state. We're working on getting AMP plugin v2.1 out the door (which includes the hero image prerendering), and once that's out we'll be able to focus on other Optimizer improvements.

**Pull request closed without merging**
