### PR TITLE
add WordAds Sanitizer

### PR DESCRIPTION
**Pull request by eduardogoncalves**
Add WordAds Sanitizer.

Convert this:
```php
<div class="wpcnt ">
<div class="wpa">
<span class="wpa-about">Advertisements</span>
<div id="ac-belowpost" class="u belowpost">
<div style="padding-bottom:15px;width:300px;height:250px;float:left;margin-right:5px;margin-top:0px;">
<div id="atatags-1435831621">
<script data-cfasync="false" type="text/javascript">
				__ATA.cmd.push(function() {
					__ATA.initSlot('atatags-1435831621',  {
						collapseEmpty: 'before',
						sectionId: '1435831621',
						width: 300,
						height: 250
					});
				});
				</script>
<div id="crt-1411307602" style="width:300px;height:250px;display:none !important;"></div>
<script data-cfasync="false" type="text/javascript">
		(function(){var c=function(){var a=document.getElementById("crt-1411307602");window.Criteo?(a.parentNode.style.setProperty("display","inline-block","important"),a.style.setProperty("display","block","important"),window.Criteo.DisplayAcceptableAdIfAdblocked({zoneid:388248,containerid:"crt-1411307602",collapseContainerIfNotAdblocked:!0,callifnotadblocked:function(){a.style.setProperty("display","none","important");a.style.setProperty("visbility","hidden","important")}})):(a.style.setProperty("display","none","important"),a.style.setProperty("visibility","hidden","important"))};if(window.Criteo)c();else{if(!__ATA.criteo.script){var b=document.createElement("script");b.src="//static.criteo.net/js/ld/publishertag.js";b.onload=function(){for(var a=0;a<__ATA.criteo.cmd.length;a++){var b=__ATA.criteo.cmd[a];"function"===typeof b&&b()}};(document.head||document.getElementsByTagName("head")[0]).appendChild(b);__ATA.criteo.script=b}__ATA.criteo.cmd.push(c)}})();
		</script>
</div>
</div> <div style="padding-bottom:15px;width:300px;height:250px;float:left;margin-top:0px;">
<div id="atatags-1435831624">
<script data-cfasync="false" type="text/javascript">
				__ATA.cmd.push(function() {
					__ATA.initSlot('atatags-1435831624',  {
						collapseEmpty: 'before',
						sectionId: '1435831624',
						width: 300,
						height: 250
					});
				});
				</script>
<div id="crt-13815610" style="width:300px;height:250px;display:none !important;"></div>
<script data-cfasync="false" type="text/javascript">
		(function(){var c=function(){var a=document.getElementById("crt-13815610");window.Criteo?(a.parentNode.style.setProperty("display","inline-block","important"),a.style.setProperty("display","block","important"),window.Criteo.DisplayAcceptableAdIfAdblocked({zoneid:837497,containerid:"crt-13815610",collapseContainerIfNotAdblocked:!0,callifnotadblocked:function(){a.style.setProperty("display","none","important");a.style.setProperty("visbility","hidden","important")}})):(a.style.setProperty("display","none","important"),a.style.setProperty("visibility","hidden","important"))};if(window.Criteo)c();else{if(!__ATA.criteo.script){var b=document.createElement("script");b.src="//static.criteo.net/js/ld/publishertag.js";b.onload=function(){for(var a=0;a<__ATA.criteo.cmd.length;a++){var b=__ATA.criteo.cmd[a];"function"===typeof b&&b()}};(document.head||document.getElementsByTagName("head")[0]).appendChild(b);__ATA.criteo.script=b}__ATA.criteo.cmd.push(c)}})();
		</script>
</div>
</div>
</div>
</div>
</div>
```
to this:
```php
<div class="wpcnt ">
    <div class="wpa">
        <span class="wpa-about">Advertisements</span>
        <div id="ac-belowpost" class="u belowpost">
            <div class="amp-wp-inline-53a39aef51eef89b8c05747e9ce154ee">
                <div id="atatags-1435831621">
                    <amp-ad type="pubmine" data-section="1" data-pt="1" data-ht="2" data-siteid="143583162" width="300" height="250"></amp-ad
                </div>
            </div>
            <div class="amp-wp-inline-a152b09cda2c5f8c3eed282d975e618a">
                <div id="atatags-1435831624">
                    <amp-ad type="pubmine" data-section="4" data-pt="1" data-ht="2" data-siteid="143583162" width="300" height="250"></amp-ad>
                </div>
            </div>
        </div>
    </div>
</div>
```

### CODE REVIEW

**Comment by westonruter** [comment]
@eduardogoncalves is this for markup that is output by the [AdControl](https://wordpress.org/plugins/radcontrol/) plugin? If so, it really needs to be submitted as a pull request to that plugin's repo instead: https://github.com/Automattic/RadControl

**Comment by eduardogoncalves** [comment]
@westonruter Ok. The best way of doing this is to add a filter on 'amp_content_sanitizers' to hook my class?

**Comment by westonruter** [comment]
Actually as you just suggested over Slack, it would be even better to check at the point where the markup is output if `function_exists('is_amp_endpoint') && is_amp_endpoint()` and output the AMP markup from the start.

**Comment by westonruter** [comment]
See https://github.com/Automattic/RadControl/pull/7

**Pull request closed without merging**
