### PR TITLE
Update Gutenberg packages after v11.4.1 release

### PR DESCRIPTION
**Pull request by pierlon**
This set of package releases now bump Webpack to v5 so we need to make sure the Webpack plugins we're using are supported.

### Changes

- Bump `copy-webpack-plugin` Webpack plugin to v9.0.1
- Bump `webpackbar` Webpack plugin to v5.0.0-3 
- Replace `optimize-css-assets-webpack-plugin` Webpack plugin with `css-minimizer-webpack-plugin` that supports Webpack 5

### CODE REVIEW

**Comment by pierlon** [comment]
The `@wordpress/scripts` dependency has been updated to utilize Webpack 5 so it's gonna take a few changes to get this PR ready for merging.

**Comment by delawski** [comment]
It [turns out](https://webpack.js.org/migrate/5/) that:

> webpack 5 does no longer include a polyfill for this [`process`] Node.js variable. Avoid using it in the frontend code.

And indeed, I'm getting the following error when visiting the Onboarding Wizard or Settings page:

Screenshot 2021-08-25 at 11 19 50

It's caused by the [`useReducedMotion`](https://github.com/WordPress/gutenberg/blob/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/compose/src/hooks/use-reduced-motion/index.js) hook. A few days ago the hook has been [updated](https://github.com/WordPress/gutenberg/commit/914f543e1e50d8c65c05a417efbdf539ef0d7a63#diff-efc4b0a669e3d5cf86848741647e67bebcd7cd4b91c1d0ee84bc5fa9d5ebeafb) to no longer use the `process` variable but this version is not yet released.

As a workaround, I tried installing the `process` package manually and then adding the `resolve.fallback.process = require.resolve( 'process/browser' )` to the Webpack config, as suggested in the [docs](https://webpack.js.org/configuration/resolve/#resolvefallback). It didn't work for me.

It seems that the cleanest and simplest solution would be to wait for the next `@wordpress/compose` release, if possible.

**Comment by pierlon** [comment]
> It seems that the cleanest and simplest solution would be to wait for the next `@wordpress/compose` release, if possible.

Seems that it was shipped with v5.0.2 of the package 🎉.

**Comment by pierlon** [comment]
@delawski would love to get your review on this.

**Comment by delawski** [comment]
I checked out the branch and I'm no longer getting this `ReferenceError: process is not defined` error (or any other error) 🎉

One thing to note, though, is that when running the `npm install/ci` I'm getting some npm warnings.

If I'm on the recommended `lts/*` Node version (through the `.nvmrc` file), I'm getting the following:

```console
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: undefined,
npm WARN EBADENGINE   required: { node: '>= 15', npm: '>= 7' },
npm WARN EBADENGINE   current: { node: 'v14.17.5', npm: '7.21.0' }
npm WARN EBADENGINE }
```

If I switch to Node 15, I'm getting even more warnings:

```console
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.10.7',
npm WARN EBADENGINE   required: { node: '^12.20 || ^14.14.0 || ^16' },
npm WARN EBADENGINE   current: { node: 'v15.14.0', npm: '7.18.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'comment-parser@1.2.3',
npm WARN EBADENGINE   required: { node: '^12.20 || ^14.14.0 || ^16' },
npm WARN EBADENGINE   current: { node: 'v15.14.0', npm: '7.18.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@36.0.7',
npm WARN EBADENGINE   required: { node: '^12.20 || ^14.14.0 || ^16' },
npm WARN EBADENGINE   current: { node: 'v15.14.0', npm: '7.18.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'comment-parser@1.2.3',
npm WARN EBADENGINE   required: { node: '^12.20 || ^14.14.0 || ^16' },
npm WARN EBADENGINE   current: { node: 'v15.14.0', npm: '7.18.1' }
npm WARN EBADENGINE }
```

Only if I switch to Node 16, I get no build-time warnings.

What do you think about updating the `.nvmrc` file to version `16`?

**Review by delawski — APPROVED** [review]
LGTM 🚢

**Comment by pierlon** [comment]
> What do you think about updating the `.nvmrc` file to version `16`?

@delawski We could downgrade it back to v14.7 since that's the current LTS release for node. I bumped it to v15 in https://github.com/ampproject/amp-wp/pull/6001/commits/5cc2339bf0adc8e6e675981b62562b5becc5ca3e but there was no real reason for that change.

**Comment by delawski** [comment]
@pierlon I agree. Other than those couple of warnings in the console, there's no real reason to update the Node version. Let's keep it as is.

**Pull request merged**
