### PR TITLE
Support extra attributes for amp-iframe

### PR DESCRIPTION
**Pull request by pdufour**

### CODE REVIEW

**Comment by westonruter** [comment]
@pdufour Would you please elaborate on the changes here? According to the spec, I don't that `amp-iframe` supports `heights` or `media` attributes: https://www.ampproject.org/docs/reference/components/amp-iframe#attributes

**Comment by pdufour** [comment]
They are common attributes for all amp elements that support `layout=responsive`

https://www.ampproject.org/docs/reference/common_attributes#heights

http://jsbin.com/nacecaboqi/edit?html,output (Scroll down for iframe)

**Comment by westonruter** [comment]
Can you provide some steps to reproduce the problem? I pasted the AMP HTML from http://jsbin.com/nacecaboqi/edit?html,output into post content and `heights` attribute was not stripped out.

**Comment by westonruter** [comment]
Also, can you re-check in the `develop` branch now that #823 has been merged?

**Comment by pdufour** [comment]
You're right, I'm on an old branch. It is working with the `heights` attribute. I assume the `iframe-sanitizer` is deprecated now?

**Comment by westonruter** [comment]
No, `iframe-sanitizer` isn't deprecated, but the `heights` attribute is not HTML5 so it isn't something that would be sanitized from an `iframe` tag to convert to `amp-iframe`.

**Pull request closed without merging**
