### PR TITLE
Remove requirement for analytics to entries to have type supplied

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

This addresses an issue raised in [support topic](https://wordpress.org/support/topic/using-in-house-custom-analytics-causes-javascript-errors/) where in-house analytics (which are supposed to lack a `type` attribute) are 

* Remove `required` attribute from Type input field and server-side validation.
* Omit `type` from `amp-analytics` tag when Type is empty.
* Remove the unnecessary readonly ID input field from the form entries.
* Use UUID to generate unique IDs rather than hashing type and contents.
* Stop needlessly showing truncating ID in entry heading on admin screen, and use ordered list instead to differentiate entries.

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by westonruter** [comment]
Rather than being satisfied with this as-is, in 1.6+ I'd rather see this Analytics screen removed entirely and moved into an “Advanced” area of the main settings screen. This section would be collapsed by default. We'd use the REST API to update the Analytics and get rid of the current codebase entirely. See #2317.

**Comment by pierlon** [comment]
Removing this from the v2.1 milestone since it's already been fixed in #5155.

**Comment by westonruter** [comment]
~Moved to v2.0~

**Comment by westonruter** [comment]
Oh, woops. This PR was not merged. It is obsolete.

**Pull request closed without merging**
