### PR TITLE
Eliminate "AMP Settings" panel from Gallery block and move them to AMP advanced settings

### LINKED ISSUE #4989: Eliminate "AMP Settings" panel from Gallery block
## Feature description

In the theme of preventing the user from having to know anything about AMP (#4554, #4555, #4556, #4557) to author content, we should also consider eliminating the dedicated “AMP Settings” panel from the Gallery block:

image

At one level this could just be a matter of removing “AMP” from the panel title. It could also mean moving the toggles under “Advanced”.

We also need to take into account how other plugins extend the Gallery block. Jetpack for example has this setting:

image

When that is enabled (as of Jetpack 8.7) the effect is as if the two toggles in AMP settings have been turned on. Users will be confused as to what purpose they have when this Jetpack feature is enabled. 

Perhaps the AMP-provided settings panel should be made easy for another plugin to turn off (e.g. Jetpack).

We should also consider whether this functionality belongs in the AMP plugin in the first place, and if it should be removed/deprecated in favor of ecosystem plugins (like Jetpack). 

Jetpack's implementation is key because it provides a non-AMP version on non-AMP pages. The AMP plugin doesn't currently provide that, which is yet another source of confusion for users. If a site is in a paired AMP setup (Reader/Transitional mode), why should there be AMP-specific settings present in the first place if functionality won't be working in the canonical (non-AMP) version of the page? 

We should limit extending blocks with AMP functionality when that functionality can be used on any version of the page. This will be greatly facilitated by Bento AMP. However, in the meantime, we should consider whether this functionality should be in the AMP plugin or relegated to the ecosystem.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by thelovekesh**
## Summary

This PR aims to move `AMP Settings` panel from the gallery block to advanced settings.

Fixes #4989 

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by thelovekesh** [comment]
Failing tests have been fixed in - #7158

**Comment by westonruter** [comment]
As I understand, this PR moves the gallery/lightbox settings from an individual block to be a global settings. I don't think will work out because a user may want a carousel for one gallery block but not have it for another block. I realize #4989 is not particularly clear as it was more of a issue for more discovery, but I recall the idea for global settings was whether to control whether the block-specific settings would be exposed. For example, let's say you are using Jetpack and all galleries already have lightboxes. In that case, the checkbox for AMP lightbox is redundant and shouldn't be presented to all users for every single block.

Instead of removing the AMP-specific toggles, can the AMP toggles be moved to the Advanced panel so as to eliminate the AMP Settings panel?

**Comment by thelovekesh** [comment]
> For example, let's say you are using Jetpack and all galleries already have lightboxes. In that case, the checkbox for AMP lightbox is redundant and shouldn't be presented to all users for every single block.

Agree 💯 

I will move them to the `Advanced Settings` 👍🏼

**Comment by thelovekesh** [comment]
@westonruter Can you give it a round of review?

**Review by westonruter — APPROVED** [review]
LGTM!

**Pull request merged**
